env/production/replica_count.yaml
Temporarily disable HPA in production by hardcoding min/max to expected and sensible values: 2 admin, 4 API, 6 Celery workers
=> Disable HPA in prod

base/documentation-deployment.yaml
After doing a load test in staging, we saw that the CPU and memory stayed very low even under 20k requests per minute. Therefore, I'm adjusting resources accordingly.
Slack thread: https://gcdigital.slack.com/archives/CV38DBNVA/p1611084988016900
=> feat: adjust resources for documentation deployment

env/production/kustomization.yaml
Releasing https://github.com/cds-snc/notification-manifests/pull/173 to production
=> Bump production to 0.22.0

env/production/replica_count.yaml
We have been recently paged during business hours because we don't clear up the email queue fast enough. The last occurrence was [yesterday](https://gcdigital.slack.com/archives/CNWA63606/p1612378640091100).
We processed ~7000 emails/5 minutes with 6 Celery pods, this amounts to 23 emails sent per second. Our limit is at 100 emails sent per second so I'm picking up a 2.5x increase (max replicas from 6 to 15) to clear the queue faster while being under the SES rate limit.
HPA for Celery pods in production is safe compared to HPA with admin/API pods so I'd like to give this a go.
=> Update number of Celery pods in production

base/api-deployment.yaml
Fixes #226 for the API deployment.
This deployment has 2 containers
- `migrate-db`, on boot in charge of migrating the database if necessary
- `api`, regular API
the env have been added to `migrate-db` instead of `api`, this PR fixes this
=> fix: DB envs on api container not migrate-db

base/admin-deployment.yaml, base/api-deployment.yaml
Do not do database connection checks on health check endpoints used by `livenessProbes` on admin and API pods. The probe should be responsible for assessing if a single pod is healthy, a slow database connection will make the entire service appear to be unhealthy and will create a cascading failure (all API pods and then all admin pods).
We can pass a `simple` query param to admin and API services to skip the database connection https://github.com/cds-snc/notification-api/blob/10df7c236d431f6653c3a9e1990f93cfc4cdc6aa/app/status/healthcheck.py#L16-L19
Demo:
- https://notification.canada.ca/_status?simple=true
- https://api.notification.canada.ca/_status?simple=true
Trello card: https://trello.com/c/yCDSXWsm/305-do-not-connect-to-db-on-liveness-probes
=> feat: do not connect to DB for admin/API liveness probes

base/ipv4-deployment.yaml
Allocate a minimum of CPU and memory to the IP geolookup deployment.
Set to double what it was currently using when I looked at the data
```
kubectl top pod ipv4-8578d99fc-ncblp 
NAME                   CPU(cores)   MEMORY(bytes)   
ipv4-8578d99fc-ncblp   26m          41Mi
```
=> Set CPU and memory for ipv4 deployment

base/admin-deployment.yaml, base/api-deployment.yaml
Stop relying on [the fallback value in `config.py`](https://github.com/cds-snc/notification-admin/blob/f947e0d2053b372d2321670dcf7d0260287dba8d/app/config.py#L32), the fallback mechanism is going away soon. Introduces the env variable on the API side as well, it will be needed in https://github.com/cds-snc/notification-api/pull/1241
=> feat: add env DOCUMENTATION_DOMAIN in admin and API

env/production/kustomization.yaml
- [Update AWS CLI when building containers (#1242)](https://github.com/cds-snc/notification-api/commit/50bebbae344fc5ba0a9df4599abaac1dd6b08bf6) by Antoine Augusti
- [Rate limit settings (#917)](https://github.com/cds-snc/notification-admin/commit/64c8ae52ec0e221e7b3e9841dadfd07e966e73e4) by Ren-David
- [Update AWS CLI when building containers (#27)](https://github.com/cds-snc/notification-document-download-api/commit/e577c8b13d089290b21a9f220a5a6cdb178152fd) by Antoine Augusti
- [Increase keepalive between Gunicorn and LB …
=> [AUTO-PR] Automatically generated new release 2021-03-03T20:42:24.912Z

env/production/kustomization.yaml
- [Beta - Navigation overhaul (#904)](https://github.com/cds-snc/notification-admin/commit/d614c30ad22971e3d06ceb32d695e1d84477ffab)
=> Update notify-admin to d614c30

env/production/kustomization.yaml
Releases:
- 0.29.0 https://github.com/cds-snc/notification-manifests/pull/257
- 0.30.0 https://github.com/cds-snc/notification-manifests/pull/260 (doesn't affect production, tag was only relevant to staging)
=> Bump production to 0.30.0

env/production/replica_count.yaml
Lower the number of Celery pods while we work on some other performance issues related to CPU/database connections.
=> Reduce max number of Celery pods in production

env/production/kustomization.yaml
Release https://github.com/cds-snc/notification-manifests/pull/274 to production.
On the admin side, https://github.com/cds-snc/notification-admin/pull/919 needs it.
=> Bump production to 0.31.0

env/production/kustomization.yaml
- [fix: translate a section title on Why Notify (#955)](https://github.com/cds-snc/notification-admin/commit/ebcad0fbe47d444a0a46eab3cb5a3d99180e310e) by Antoine Augusti
- [Make 'trial mode' more concise when used as a descriptor (#952)](https://github.com/cds-snc/notification-admin/commit/904761007949fbf66301d1b5efe1dbd1b37a8a89) by Anik Brazeau
- [fix: Added aria-expanded attribute on menu buttons …
=> [AUTO-PR] Automatically generated new release 2021-03-17T13:29:56.602Z

base/document-download-api-deployment.yaml, base/document-download-frontend-deployment.yaml
Now that we are going to start sending more attachments, make sure that those deployments are more robust:
- `RollingUpdate` strategy for deployments, for 0 downtime deployments
- Define CPU + memory `requests` and `limits` to give pods a minimum amount of resources to run
- Add `readinessProbe`s to make sure new pods are not serving trafic when the Docker container is not ready yet
Trello card: https://trello.com/c/OSYe4SV2/386-make-document-download-k8s-deployments-more-robust
=> feat: improve document download deployments

base/api-deployment.yaml
Adding ASSET_DOMAIN which is not defined within notification-api container. 
ASSET_DOMAIN within the code defaults to the production address
=> fix: adding ASSET_DOMAIN to the api container

env/staging/cwagent-fluentd-quickstart.yaml
Publish StatsD metrics to CW every minute instead of every 5 minutes.
Agents run on each nodes, they are collected every `metrics_collection_interval` to a single agent and aggregated/sent to CW every `metrics_aggregation_interval`.
AWS doc: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-custom-metrics-statsd.html
=> feat: collect StatsD metrics more often

env/production/kustomization.yaml
- [Added route notification to bulk queue for spreadsheets larger than 1,000 rows (#1296)](https://github.com/cds-snc/notification-api/commit/0adeda4baf677cd86efc737b73f05ecf35e60bce) by Jimmy Royer
=> [AUTO-PR] Automatically generated new release 2021-05-18T13:22:40.102Z

env/production/kustomization.yaml
- [feat: notify service users when updating their daily limit (#1298)](https://github.com/cds-snc/notification-api/commit/1f4cba15a20ec8d4f1c700d6552af5c4af3c0adb) by Antoine Augusti
- [feat: remove env.enc files (#1032)](https://github.com/cds-snc/notification-admin/commit/110ec4dca1798f3b40a69b6f3efc2320b5041a1e) by Antoine Augusti
- [Fix French Typo "personnalisation" (#1033)](https://github.com/cds-snc/notification-admin/commit/bffcd3b5546c5c20d7f1a8218cc549b543d98912) by Anik Brazeau
- [feat: document multiple callbacks per notification (#80)](https://github.com/cds-snc/notification-documentation/commit/beca3016b29e2c85b0b22059aea72049b41fdd60) by …
=> [AUTO-PR] Automatically generated new release 2021-05-19T22:08:35.593Z

env/production/kustomization.yaml
Latest image of admin does not work. Reverting to last image of notification-admin that built OK at this commit:
https://github.com/cds-snc/notification-admin/commit/615a33274e0f6af9c5152ad9a7d8cb39c09f72c5
This should remove these commits from the notification-admin built image:
* [update docker.yaml workflow to use setup node action (#1079)](https://github.com/cds-snc/notification-admin/commit/d6ce98bcffa611d19d5f23464f32a3dce9318f6a) by Omar Nasr
* [Add more help for installing python (#1077)](https://github.com/cds-snc/notification-admin/commit/6592449133b8bf3baaf63d0ef25aed90166a9486) by Steve Astels
=> Revert to previous version of admin with a working build

env/production/kustomization.yaml
Latest image of admin does not work. Reverting to last image of notification-admin that built OK at this commit:
cds-snc/notification-admin@c3b47a1
This should remove these commits from the notification-admin built image:
* [update docker.yaml workflow to use setup node action (#1079)](https://github.com/cds-snc/notification-admin/commit/d6ce98bcffa611d19d5f23464f32a3dce9318f6a) by Omar Nasr
* [Add more help for installing python (#1077)](https://github.com/cds-snc/notification-admin/commit/6592449133b8bf3baaf63d0ef25aed90166a9486) by Steve Astels
* [Content tweaks (#1076)](https://github.com/cds-snc/notification-admin/commit/615a33274e0f6af9c5152ad9a7d8cb39c09f72c5) by Anik Brazeau
=> Updating to previous image which *actually* built ok

env/production/kustomization.yaml
The bump includes these changes:
* https://github.com/cds-snc/notification-manifests/pull/494
* https://github.com/cds-snc/notification-manifests/pull/535
* https://github.com/cds-snc/notification-manifests/pull/568
Most of these changes were applied directly to both staging and production, as these were mostly environment variables manipulation. These are not versioned under `kubectl` bases, which includes a revision. So this is mostly a symbolic upgrade.
=> Bump production to 0.37.3

env/production/kustomization.yaml
We are having tons of celery error at the moment. Reverting previous release.
=> Revert previous deployment of API

base/api-deployment.yaml
I made an oopsie and realised I added the variable to the init container but not the application one. So I fixed that
=> fix: adding variable to application container

base/admin-deployment.yaml, base/api-deployment.yaml
Tweaking the readiness probe for both admin and API components to remove the database check. For now, removing it will prevent these to go down if the database is slowed to a point that the components can't reply in a timely manner. The API component especially should not go down and stop processing because the database is in `autovacuum` processing.
More details in the [ADR for the database bottleneck](https://github.com/cds-snc/notification-adr/pull/1).
=> feat: Detach the database check from the k8s readiness probe

env/production/kustomization.yaml
Includes following changes:
* [feat: enable feature flag for notification persistence in celery for staging environment](https://github.com/cds-snc/notification-manifests/pull/569)
* [fix: notification persistence feature flag typo](https://github.com/cds-snc/notification-manifests/pull/578)
* [fix: adding variable to application container](https://github.com/cds-snc/notification-manifests/pull/586)
* [feat: Detach the database check from the k8s readiness probe](https://github.com/cds-snc/notification-manifests/pull/602)
* [fix cannot have missing env variables](https://github.com/cds-snc/notification-manifests/pull/606)
=> Bumping manifest version

env/staging/replica_count.yaml
lower max number celery workers to see if it helps with scaling
=> lower max celery workers

env/staging/replica_count.yaml
This reverts commit d8f25e0069addd11b64373126f158eb054d10321.
Part of Omar's testing in staging involved seeing if reducing the number of celery workers would reduce database reads and transitively reduce the read loads experienced in staging. We should eventually revert this test to re-align with what we have in production, unless we decide to change the latter as well.
=> Revert "lower max celery workers (#634)"

env/production/kustomization.yaml
Reverting to previous release of 2f0eb99 for the notification API after we observe that a queue is blocked. It seems a `None` value slips through for the queue to use. We are still investigating why but we are proceeding to the revert to unblock SMS sent through CSV uploads in production.
=> Revert to previous API release #2f0eb99

.github/workflows/merge_to_main_production.yaml
Change action to deploy api lambda to production
Action changes needed for the new api lambda
=> Release api lambda

.github/workflows/syntax_check.yaml
Removed redirection to /dev/null for kubectl customize command.
We could not quickly assess the reason for the failed build following the `kubectl kustomize`  command from that build. We would like to have all the output for now even if that is a long output. Better than silence.
=> Removed redirection to /dev/null for kubectl kustomize command.

base/api-deployment.yaml
Only added `FF_REDIS_BATCH_SAVING` to the `migrate-db` pod before. Why do we have all our env vars in the `migrate-db` pod, anyway?
=> add to both apis

env/production/replica_count.yaml
We went through an incident this week where two clients hit the API hard for a short amount of time, possibly the root cause of bringing the API Kubernetes pod instances into an out of memory state. This caused restarts and a few messages to be dropped (around 20-25 observed in AWS CloudWatch / Logs Insights).
=> Reset the API HPA to previous values, 4min/8max scalability

.github/workflows/merge_to_main_production.yaml, env/production/kustomization.yaml
- [Increased cache TTL for daily service limit to 2h (#1464)](https://github.com/cds-snc/notification-api/commit/a84a71ddd3309abefdcbdeb13d9f199211941ec2) by Jimmy Royer
- [Periodic Transition of expired In-Flight SMS/Email (#1456)](https://github.com/cds-snc/notification-api/commit/ba7212a91d484e1face2e4ffbbb9a02731f3340f) by Ikenna
- [Fix the database slow loading of total notifications for a service …
=> [AUTO-PR] Automatically generated new release 2022-02-16T15:00:02.118Z

env/staging/cwagent-fluentd-quickstart.yaml
> CloudWatch agent embedded metrics processing was accidentally configured under the logs block when it should have been under the metrics block.
=> fix: configure emf correctly

env/production/cwagent-fluentd-quickstart.yaml
> Enable CloudWatch embedded listener service in production.
=> feat: cloudwatch agent listen for emf (prod)

env/production/cwagent-fluentd-quickstart.yaml, env/staging/cwagent-fluentd-quickstart.yaml
> Embedded metrics was enabled, however the corresponding default port `25888` was not exposed, resulting in the agent refusing the connection.
=> chore: allow connections to emf port

env/production/cwagent-fluentd-quickstart.yaml, env/staging/cwagent-fluentd-quickstart.yaml
> The name `metrics` is misleading in the config. After reviewing the docs again, the original configuration was correct. This misconfiguration was detected when reviewing the cloudwatch agent logs and it throwing a `Configuration validation first phase failed` error when it detected an unexpected value under the `metric` block.
=> fix: move emf config back to logs

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/scripts/notify-dev-entrypoint.sh
Add kubectl, kubens, AWS cli and aliases to make manifest
support and development easier.
This includes `k-staging` and `k-prod` aliases that will make it easier to configure our kubeconfig file.
* Closes cds-snc/notification-planning#426
=> fix: update the devcontainer with k8s tools

env/staging/replica_count.yaml
In order to test the theory if the file descriptors limit is reach on the nodes with the document-download-api components or if it's gunicorn reaching its limit somehow, this change increases the number of auto scale from `2` to `4`. If it fixes the crashing doc-api, the latter is true (gunicorn was overloaded) but if it does not, it should exacerbate the file descriptors issue (if true).
=> Autoscale to 4 instances in staging the env for doc-api

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Octant provides a dashboard that makes it easier to manage
Kubernetes workloads.
* cds-snc/notification-api#1491
=> feat: add Octant to devcontainer

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, base/api-deployment.yaml, base/celery-deployment.yaml, env/production/cwagent-fluentd-quickstart.yaml, env/staging/cwagent-fluentd-quickstart.yaml, env/staging/replica_count.yaml
> Sending metrics via TCP is causing a-lot of open connections. Exposing the agent's UDP port to test performance when metrics are sent via UDP.
=> feat: enable sending metrics via udp

env/production/replica_count.yaml
After perf testing the batch saving feature in staging with a max replica count of 4 for document-download-api, we propagate the change to production. Our test results showed configuration change led to a more stable environment with batch saving enabled, as the data stream is quicker and hits the download api quicker, we need more instances to respond.
=> Increased replica max count of document-download-api to 4 in prod

env/production/kustomization.yaml, env/staging/kustomization.yaml
Add environment variables to the kustomize build that are defined
but not replaced.  The result of this change is that instead of
the manifests containing values of `$(VAR_NAME)`, they will
have the value set in the environment's `.env` file.
- **Staging:** Add `SENSITIVE_SERVICES` variable.
- **Production:** Add `GC_ARTICLES_API_AUTH_*` variables.
In both cases, the current `.env` value is blank `""`. 
* #969 
* cds-snc/notification-planning#421
=> fix: missing environment variables in kustomize build

.github/actions/test-manifest/action.yaml, .github/workflows/syntax_check.yaml
Add an action that tests a Kustomize manifest build to check
if it can build successfully and there are no environment
variables that are not used or replaced.
* cds-snc/notification-planning#421
=> feat: add test manifest build action

.github/workflows/autopr_merged.yaml
This PR introduces automation that will trigger the deployment of new releases automatically when the Notify PR bot auto-generated release is merged.
This is done by tracking merged pull requests containing the title [AUTO-PR]. PR's containing the title of [MANIFEST] will also trigger the same process, so that changes to the Kubernetes config can be automatically deployed using the tag system.
This is done by using a new GitHub workflow to bump the `VERSION` file in the root directory, and to update the main branch with this change. Manual intervention will no longer be required when releasing updates to the apps managed by this repo. To achieve this, this new GitHub worklow will disable branch protection, push the update to the version file, and then re-enable branch protection.
[Demo …
=> feat: automatically release to production when the auto-pr bot release is merged

.github/workflows/autopr_merged.yaml, .github/workflows/merge_to_main_production.yaml
Workflow tweak to no longer prefix with a `v` and to checkout the base branch
=> fix: tweak checkout step to not prefix

.github/workflows/autopr_merged.yaml, .github/workflows/merge_to_main_production.yaml
Update the workflow so that the release automation uses the pr-bot GitHub token to interact with the repo. This is required since GitHub prevents the triggering of workflows when the GitHub action token is in play.
Documented [here](https://docs.github.com/en/enterprise-server@2.22/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)
PR also removes the "Merge to main (production)" workflow trigger on the workflow file.  This is because we now only want a production deploy to occur once the new `VERSION` file is pushed to `main` by the auto PR workflow.
=> chore: provide pr bot token when checking out

.github/workflows/sync_secrets_production.yaml
> Sync production secrets to secretsmanager so that it's available to lambda functions
=> feat: sync prod secrets to secretsmanager

.github/workflows/sync_secrets_production.yaml, .github/workflows/sync_secrets_staging.yaml, .gitignore
> Sync secrets only when envs change and after the merge workflows complete
=> feat: only update envs when values change

base/admin-deployment.yaml, env/production/kustomization.yaml, env/staging/kustomization.yaml
There is no config map defined for GC_ARTICLES_API in the Kubernetes configuration, hence that one is missing in staging and production. This is following the [bump to v0.50.7](https://github.com/cds-snc/notification-manifests/pull/1038) where we discovered it might not work properly and rather fallback to the config in the Python configuration (where production might fallback to staging value; so nothing broken or at risk but an env mismatch we don't want).
=> Added GC_ARTICLES_API URL value to env config map

Makefile
Update the `env-keys-$ENV_NAME` Makefile targets 
so that they can handle `"` quote characters
in the variable value.
=> fix: Makefile target to generate env keys

.github/workflows/sync_secrets_production.yaml, .github/workflows/sync_secrets_staging.yaml
Clarifying a step description to better describe purpose on redeployment trigger by environment changes.
=> Reworking comment for redeploymenton env changes

base/alb-ingress-controller.yaml
This upgrades the AWS load balancer manifest to v2.4.1, which is
required by Kubernetes v1.22 due to deprecated API removal.
To validate:
```sh
curl -Lo v2_4_1_full.yaml https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/download/v2.4.1/v2_4_1_full.yaml
diff v2_4_1_full.yaml base/alb-ingress-controller.yaml
```
```diff
<         - --cluster-name=your-cluster-name
---
>         - --cluster-name='$(CLUSTER_NAME)'
```
This has been applied manually in Staging already and needs to 
merge before any other manifest PRs are applied.
* cds-snc/notification-planning#643
* cds-snc/notification-planning#555
=> feat: upgrade AWS load balancer controller v2.4.1

.github/workflows/merge_to_main_production.yaml, .github/workflows/merge_to_main_staging.yaml
This is to address aws/aws-cli#6920 until an upstream fix is provided for
the AWS cli:
```
Run kubectl apply -k env/staging --kubeconfig=/home/runner/.kube/config
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
Error: Process completed with exit code 1.
```
=> fix: pin kubectl to v1.23.6

.github/workflows/merge_to_main_production.yaml, env/production/kustomization.yaml
- [fix: publish new lambda version and update alias (#1543)](https://github.com/cds-snc/notification-api/commit/66fb4a2a9147ba56d4eb89f2d13ab74dc68d1109) by Pat Heard
- [Priority lanes 629 (#1536)](https://github.com/cds-snc/notification-api/commit/1d6fe5d289487f4d85c3e8e35d6f8ff3954ecbd5) by Andrew
- [Added new relic config (#1540)](https://github.com/cds-snc/notification-api/commit/38152c35a5e477ae6ea5753d2ec4fe4b11949269) by Jimmy Royer
- …
=> [AUTO-PR] Automatically generated new release 2022-05-10T14:01:46.308Z

env/production/kustomization.yaml
Reverts cds-snc/notification-manifests#1186
```
document-download-api-7b4cc7d64f-w7bgq      0/1     CrashLoopBackOff   4 (70s ago)   4m24s
```
Also, turns out staging was working because the old pod was still running 😞
=> Revert "[AUTO-PR] Automatically generated new release 2022-07-26T17:22:33.053Z"

.github/workflows/merge_to_main_production.yaml, env/production/kustomization.yaml
- [Add missing dependency (#1651)](https://github.com/cds-snc/notification-api/commit/a1db924dc870546d10c8a9352563e615f5d501ef) by Stephen McMurtry
- [Fix for bug where user can schedule and send more SMS than daily limit allows (#1645)](https://github.com/cds-snc/notification-api/commit/ae8b1c831e80b34738084dcb80405e7a8a101c14) by Stephen McMurtry
- [Confusing error message for sms limit reached …
=> [AUTO-PR] Automatically generated new release 2022-10-25T14:40:48.143Z

Makefile
We want to check diffs against what is in current staging and prod and not local stg/prd
When manifest changes, we need to check the change against origin, not against our local checked out version of main.
I tested this by changing main (locally), making a new branch (locally) and running `make diff-staging`
It checks the result against local main. 
With my changes, I see the correct result
=> Change make-diff to check again origin

base/celery-deployment.yaml, base/celery-hpa.yaml
Increasing the memory limit on celery pods to 1024Mi. Also configure horizontal auto scaler to scale out based on memory usage
Celery is running into OOM errors in production due to relatively low memory limits. Additionally, the horizontal pod autoscaler (HPA) is not currently configured to monitor memory usage.
=> Fix: Celery resource usage and performance tuning

.github/workflows/smoke_test.yaml
Change smoke test github action to use poetry
Essentially copied from https://github.com/cds-snc/notification-api/blob/main/.github/workflows/test.yaml#L34-L39
Run of the new action: https://github.com/cds-snc/notification-manifests/actions/runs/4501158321/jobs/7921211713?pr=1551
=> chore: use poetry for smoke test

.github/workflows/smoke_test.yaml
Had an extra "s" in #1587 . Not that [pr-bot names the branches "release-..."](https://github.com/cds-snc/notification-pr-bot/blob/main/github.js#L46)
=> chore: delete extra s in smoke test action filter

env/production/aws-auth-configmap.yaml, env/production/kustomization.yaml, env/staging/aws-auth-configmap.yaml, env/staging/kustomization.yaml
The aws-auth configmap in kube-system will be patched to allow the notification-admin-apply role to authenticate against the cluster
We are switching the authenticated user in github actions to an OIDC managed one. This configuration update will provide the necessary permissions.
=> AWS-Auth configmap in Kustomize

env/staging/aws-auth-configmap.yaml
Followup to #1644 , add roles for a few more repos
=> fix: add more OIDC roles to k8s

env/staging/replica_count.yaml
Document download and documentation scale up to 2 pods
Setting the minimum pods for all deployments to 2 in prep for k8s upgrade.
=> Setting minimum replicas for doc download and documentation to 2

env/production/replica_count.yaml
Documentation and Document Download APIs will scale out to 2 pods minimum. This is in preparation for the K8s upgrade so that there will always be at least one pod running.
Required for ensuring no downtime while upgrading k8s to 1.23
=> [MANIFEST] Scaling out prod documentation and doc download in prep for k8s upgrade

base/admin-hpa.yaml, base/api-hpa.yaml, base/celery-hpa.yaml, base/document-download-api-hpa.yaml, env/production/replica_count.yaml, env/scratch/replica_count.yaml, env/staging/replica_count.yaml
The horizontal pod autoscalers for GC Notify will be converted to the v2 api spec away from the v2beta api spec which is no longer supported as of K8s v1.24
K8s v1.24 removes support for autoscaling/v2beta api. I have converted the HPAs for notify to the new v2 api format. Tested working in my scratch account
=> HPA api version migrated from beta to v2 for k8s 1.24

env/staging/replica_count.yaml
Maximum number of celery workers will increase to 40 in staging only.
Re: Celery performance tuning
=> Upping celery HPA max to 40

base/admin-deployment.yaml, base/api-deployment.yaml, base/celery-deployment-fargate.yaml, base/celery-deployment.yaml, base/celery-sms-deployment.yaml, base/document-download-api-deployment.yaml, base/documentation-deployment.yaml
Setting termination grace period to 60 on all k8s deployments to allow for proper connection draining
This in support of doing node maintenance with k8s cordon and drain.
=> Setting termination grace period to 60

env/staging/replica_count.yaml
staging celery maxReplicas 60 -> 80
=> 80 celery pods on staging

env/staging/performance.yaml
Set celery HPA tuning to 12 pods per iteration at 45 seconds per. 
Re: Celery perf tuning
=> Setting staging HPA tuning to 12 pods per cycle at 45 seconds

env/staging/performance.yaml
This will lower the number of max celery pods in staging to 10 for @jimleroyer to investigate other performance avenues
Re: Notify perf testing
=> Lowering staging to 10 celery pods

env/scratch/celery-sms-send-deployment.yaml, env/staging/celery-sms-send-deployment.yaml
fix the name of [the script](https://github.com/cds-snc/notification-api/blob/8caba67c2c9ba58d33738dbf05854e989e92ba8d/scripts/run_celery_send_sms.sh)  
run_celery_sms_send.sh -> run_celery_send_sms.sh
=> fix: sms send script name

env/staging/performance.yaml
set sms-send maxReplicas back up to 10. Hopefully now we'll be able to scale up and stay there.
=> sms-send back up to 10 pods

env/staging/performance.yaml
Staging Celery HPA for SMS will max out at 11 pods to try and achieve 600/s
Re: SMS Perf Tuning
=> Upping celery sms hpa to 11 max pods

env/production/performance.yaml, env/staging/performance.yaml
sms-send pods only scaling to 4, this will set to 11 until we get the scaling up figured out
=> fix: force 11 sms-send pods

env/staging/performance.yaml
SMS Celery in staging will reduce to 3 minimum pods, so that we can verify the scaling issues we're seeing in production
Re: Performance tuning
=> Setting minimum pods to 3 for sms in staging

.github/workflows/merge_to_main_production.yaml
The prod k8s workflow will use the auto-retry script for kustomize apply
Re: Performance tuning
=> Changing the prod workflow to use the retry script for kustomize

env/production/node-selector-patch.yaml
Reverts cds-snc/notification-manifests#2067
Setting celery to use on demand nodes until we get the cwagent status check working properly.
=> Revert "setting prod celeries to use karpenter nodes"

env/production/performance.yaml
set the number of celery pods in production to a constant 30
Note that this will deploy to prod when its merged
=> [MANIFEST]  constant 30 celery pods

env/production/node-selector-patch.yaml
When released, celery will use Karpenter nodes again.
We have introduced a cwagent health check script that should fix the intermittent metric send errors.
Re: Celery performance tuning and node autoscaling
=> Setting production to run celery on karpenter nodes

env/staging/node-selector-patch.yaml
In staging, the API will now deploy to standard k8s nodes instead of karpenter spot instances. This is to get rid of the 502 errors we're intermittently seeing. A new card will be opened to debug that.
=> Moving API off of karpenter nodes for now while we look into 502s

base/k8s-event-logger/deployment.yaml, base/kube-state-metrics/ksm-deployment.yaml, base/notify-celery/celery-deployment.yaml, base/notify-celery/celery-sms-send-deployment.yaml, base/prometheus-cloudwatch/cwagent-deployment.yaml
We will set the logging system components to be node critical priority (IE they have the authority to kick off other pods in the event that there aren't enough resources). 
Re: Node autoscaling and performance tuning.
=> Setting system logging components to be node cricial priority

base/notify-celery/celery-deployment.yaml, base/notify-celery/celery-sms-send-deployment.yaml
The celery health probes are not working correctly in staging. Reverting them for now so we can do a manifest release. I will create a card to investigate improvements here.
=> reverting probes for celery since they aren't working properly

env/staging/performance.yaml
Currently prod has constant 11 sm-send pods. We've fixed the "sms priority queue delay on pod shutdown" issue 🤞 so we can now ramp sms pods up and down without alarms.
We've had staging scale 11 - 20 sms pods for a while, so may as well start with a max of 20.
This PR sets staging to scale 3 - 20. We can kick the tires on this and then set prod to the same.
=> feat: set staging sms minreplicas to 3

env/staging/performance.yaml
Celery HPA CPU threshold will be set to 25% in staging only. Testing to get more throughput out of SMS
=> Setting celery sms cpu threshold to 25% in staging

env/production/cwagent.yaml, env/staging/cwagent.yaml
The memory limit for cwagent in kubernetes will be set to 1gb from 200mb.
We are experiencing OOM crashes on cwagent.
=> fix: Setting higher memory limits in cwagent

env/production/node-selector-patch.yaml
Setting the celery pods to run on on-demand instances only while we sort out the imdsv2 issue with spot instances.
We are experiencing OOM errors on cwagent when using spot instances. While debugging that, we will move celery to on demand instances.
=> Setting prod celery to run on on-demads

env/staging/karpenter.yaml
IMDSv1 should be enabled for spot instances in staging after a redeploy and recycling of nodes.
We are seeing imds errors on fluentbit on spot instances due to a version mismatch.
=> Setting http tokens to optional which should enable imdsv1 

env/staging/fluentbit.yaml
Tripling membuff limit on staging celery fluentbit in order to alleviate emitter paused errors under load.
Increasing maximum memory usage for the daemonset to accommodate.
Errors in fluentbit when under load
=> Staging fluentbit membufflimit 1

env/staging/fluentbit.yaml
Celery in staging will have aliases assigned to the pipeline stages to better troubleshoot issues.
Celery MLP emitter will have an increased membuff limit to avoid lost chunks under load.
=> Fluenbit Pipeline Aliases and Celery MLP emitter Mem Buff Limit

env/staging/fluentbit.yaml
In staging Fluent bit will sleep for 10 seconds before starting up. This is to test if there is a race condition between the node and fluent bit.
Troubleshooting fluentbit stuff
=> Fluent Bit Startup Delay

env/staging/karpenter.yaml
Karpenter will have to use xlarge nodes to consolidate celery onto a single node for fluent bit emitter testing.
=> Forcing Karpenter to use large nodes for fluent bit testing

env/staging/karpenter.yaml
Setting staging to use on demand instances for karpenter for testing
=> karpenter set to on demand in staging for testing

env/staging/karpenter.yaml
Set staging back to spot instances for celery
=> reverting to spot instances

env/production/performance.yaml
The base celery (core) HPA will be re-enabled and set to 3 minimum pods scaling up to 30 as needed.
Celery performance tuning
=> [MANIFEST] Setting the minimum pods for celery core to 3

base/notify-celery-email-send/celery-email-send-deployment.yaml, base/notify-celery-main/celery-deployment.yaml, base/notify-celery-sms-send/celery-sms-send-deployment.yaml
The cloudwatch agent check will be moved to an init container. This will make sure that kubernetes is properly aware of the true celery status.
Re: Incident 2023-11-17-pod-down-sms-delay
=> Moving cwagent check outside of celery

env/production/node-selector-patch.yaml
having issues with celery pods dropping to zero. will switch to on demand for the weekend. and fix / verify next week
=> [MANIFEST] prod: switch celery back to ON_DEMAND for now

.github/workflows/merge_to_main_production.yaml, env/production/kustomization.yaml
- [Moving cwagent check outside of run celery …
=> [MANIFEST] Release 2023-11-20T14:05:26.382Z

env/dev/fluentbit.yaml, env/production/fluentbit.yaml, env/scratch/fluentbit.yaml, env/staging/fluentbit.yaml
The Fluent Bit kubernetes filter will have TLS verification disabled when talking to the kubelet. TLS is still enforced, but we do not verify the certificate... This is to test the TLS verification error we are receiving on fluent bit startup.
Re: TLS errors in fluent bit.
=> [MANIFEST] Turning off TLS verification on kubernetes filter

base/notify-celery-email-send/celery-email-send-pdb.yaml, base/notify-celery-main/celery-main-pdb.yaml, base/notify-celery-sms-send/celery-sms-send-pdb.yaml
Celery pod disruption budget will be set to two, so that there will always be at least one allowed disruption when evicting pods.
Re: Action item from failed TF worker upgrade.
=> Setting min available for celery pdb to 2

env/dev/fluentbit.yaml, env/scratch/fluentbit.yaml, env/staging/fluentbit.yaml
TLS Verify on kubelet kubernetes filter in fluent bit will be disabled to see if we can get rid of the TLS errors on startup of fluentbit
Re: Autoscaling
=> Setting TLS verify to off in fluentbit in staging

env/staging/node-selector-patch.yaml
In Staging, document download api pods will prefer 9:1 on demand nodes, but in the event that on demand nodes are not available, will allow pods to spin up on spot instances. This is to ensure that the DD Api HPA will be able to scale accordingly.
Notify Performance tuning and autoscaling
=> Staging - Document Download Pod Skew

base/notify-admin/admin-pdb.yaml, base/notify-admin/kustomization.yaml
A pod disruption budget will be added for admin so that at least one pod is always available
Downscaling nodes in prod caused admin to temporarily go down while k8s did it's thing.
=> [MANIFEST] Adding pod disruption budget for admin

env/dev/performance.yaml, env/production/performance.yaml, env/staging/performance.yaml
Changing the scale up chunks for the celeries to scale up slower, and not overload the system.
Also adjusted celery email CPU usage target back to 50 because we are seeing 30 pods even when there is low load on the system.
To be tested in staging.
Celery and node autoscaling
=> Modifying scaling behaviour for celeries

env/staging/performance.yaml
sms-send hpa is too high. under load cpu hovers at about 25%, which is the current hpa target. This PR changes the cpu requested from the nodes from 100m to 50m
=> fix: staging sms-send cpu request 100m -> 50m

env/staging/performance.yaml
Celery pods are not scaling up fast enough to process callbacks (and not even getting to max pods)
=> fix: staging celery core request 300m -> 150m

env/dev/performance.yaml, env/production/performance.yaml
We found that the sms-send and core celery pods weren't scaling all the way up. 
We tweaked a few scaling related params:
- #2264 
- #2265 
and [tested in staging yesterday](https://gcdigital.slack.com/archives/C05K8349YCR/p1702415373806189).
This PR makes corresponding changes to the prod and dev environments.
=> [MANIFEST] Adjust prod and dev scaling params

.github/workflows/merge_to_main_production.yaml
Rename the images so its tagged according to the naming convention from the Pr-bot
=> [MANIFEST] : Update merge_to_main_production.yaml

.github/workflows/helmfile_production_apply.yaml, .github/workflows/helmfile_production_plan.yaml, .github/workflows/helmfile_staging_apply.yaml, .github/workflows/helmfile_staging_plan.yaml, helmfile/overrides/tools/blazer.yaml.gotmpl
Adds workflows for Hasura and Blazer available through VPN in prod.
Also got the helmfile diff output to go to github actions comments!
VPN
=> Production and testing diff output

env/production/performance.yaml
Prod will only scale up to 15 (vs 20) pods for SMS send to try and avoid the rate limit.
Re: SMS rate limit w/ NS SMS Send
=> [MANIFEST] - Reducing prod celery sms send hpa to 15 max

helmfile/overrides/tools/blazer.yaml.gotmpl
Removing the reference to the blazer slack webhook from K8s blazer so that it starts working again.
Re: Blazer not working on VPN
=> Removing reference to blazer slack webhook

env/production/performance.yaml
Prod API HPA will only scale to 2 pods max since we don't need a ton of these and it's possible that spooling up to 8 caused node pressure.
Re: incident-2024-03-06-notify-api-pods-take-too-long-to-start-in-production
=> [MANIFEST[ Reducing k8s api to 2 max pods in prod

.github/workflows/api-rollout-k8s-staging.yaml, .github/workflows/helmfile_staging_apply.yaml, .github/workflows/helmfile_staging_plan.yaml, .github/workflows/merge_to_main_staging.yaml
The staging kustomize and helmfile workflows will be executed on the internal github runners.
Pre-requisite for private EKS
=> Staging to internal arc

helmfile/overrides/system/github-arc-scaleset.yaml.gotmpl
This will allow the github arc runners to launch docker steps inside them, by connecting to the root docker sock on the node.
This is needed for the sentinel job in the merge to staging github action.
Re: Private EKS prerequisites
=> docker in docker for sentinel

.github/workflows/merge_to_main_staging.yaml
The merge to main staging github action should now run properly on github arc.
Re: private eks prerequisites
=> chore: setting merge to main staging to run internally againg

.github/workflows/merge_to_main_staging.yaml, helmfile/overrides/system/github-arc-scaleset.yaml.gotmpl
Setting the github ARC runner to always pull latest image.
Explicitly setting the kubectl version in the installation.
Prerequisite for private eks
=> chore: ARC pullPolicy and kubectl version

.github/workflows/merge_to_main_staging.yaml
Reverting to previous GHA for merge main to staging for today - the kubectl version staging needs is too old. I'm going to have to fix manifests tomorrow.
=> chore: reverting to previous GHA for today

pull_request_template.md
Update the PR template, which is used right here in this PR. 
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/304
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on staging to verify that performance has not been affected.
- `chore:` - use for changes to non-app code (ex: …
=> Added PR template to manifests repository

helmfile/overrides/system/github-arc.yaml.gotmpl
Github ARC will now use a github app for authentication instead of a PAT
NOTE: [This Terraform PR must be merged first](https://github.com/cds-snc/notification-terraform/pull/1205)
Re: Private EKS cluster
=> Switching github arc to app id

catalog-info.yaml
Updating the metadata values of the catalog's entity.
Changing to type of entity Resource from Component.
Documentation update
N/A
=> chore: update entity kind as resource

helmfile/overrides/system/github-arc-scaleset.yaml.gotmpl
I had conditioned out using the custom docker image for github arc in production. Need to remove that condition so that the github arc runners actually run.
Re: Prep for private EKS in prod
=> [MANIFEST] - Enabling arc images in prod

helmfile/overrides/system/github-arc-scaleset.yaml.gotmpl
Setting the maximum number of runners to 20 in Github ARC. This is just preventative maintenance.
While investigating today's issue with the runners not spinning up, I figured it would be a good idea to up this number as well.
=> Upping max gha arc  runners to 20

.github/workflows/helmfile_production_apply.yaml, .github/workflows/helmfile_production_plan.yaml, .github/workflows/syntax_check_prod.yaml
The workflows supporting production releases will be updated to use the same version of kubectl and run on github arc as required
Prerequisite for private EKS cluster in production
=> Updating Supporting Workflows For Github ARC

.github/workflows/helmfile_production_apply.yaml, .github/workflows/helmfile_production_plan.yaml
For some reason the helmfile workflows for production weren't installing kubectl and helmfile 😕 
Re: release not releasing
=> Fixing helmfile workflows to install helmfile and kubectl

.github/workflows/helmfile_production_apply.yaml, .github/workflows/helmfile_production_plan.yaml, .github/workflows/helmfile_staging_apply.yaml, .github/workflows/helmfile_staging_apply_specific_app.yaml, .github/workflows/helmfile_staging_plan.yaml
To fix the issue we're seeing now with failed helmfile rollouts - I believe that the latest helmfile version is the culprit. They've moved to a 1.0.0 release candidate.
Re: Failed deployments
=> Specifying helmfile version in Github actions

.github/workflows/helmfile_production_apply.yaml, .github/workflows/helmfile_staging_apply.yaml
We weren't getting alerted on helmfile apply failures. Here's a thing to fix that.
Saw some failed releases for helmfile
=> Adding failure notifications for helmfile apply

env/production/fluentbit.yaml
Fluent Bit will be upgraded to IMDSv2 in Production
Part of IMDSv2 conversion
=> [MANIFEST] IMDSv2 for fluent bit

.github/workflows/ipv4-geolocate-webservice-staging.yaml
Fixed the kubernetes set image command that wrongly references to the `api` component rather than `ipv4`.
=> fix: API reference for the ipv4 k8 image config

.github/workflows/ipv4-geolocate-webservice-staging.yaml
Because the ipv4 image has a date suffix instead of the traditional github sha ID (there is one release per day), the github action calling its workflow needs to reference to the proper kubernetes image reference within Kubernetes by using the release tag …
=> Added support for release_tag parameter and refer in k8 image update

.github/workflows/ipv4-geolocate-webservice-staging.yaml
Adding missing param definition to the workflow, which is necessary to run it. If a parameter is missing, it cannot be passed to the workflow and available to it.
=> Adding missing param definition to the workflow

.github/workflows/ipv4-geolocate-webservice-staging.yaml
Remove unnecessary parameter to the ipv4 rollout github workflow. The release tag parameter which contains today's date will replace it.
=> Remove the git sha ID parameter for the gh action workflow

.github/workflows/merge_to_main_production.yaml, env/production/kustomization.yaml
Reverting the change here: https://github.com/cds-snc/notification-manifests/pull/2745/files
=> [AUTO-PR] Update merge_to_main_production.yaml

.github/workflows/merge_to_main_production.yaml, env/production/kustomization.yaml
Revert this morning's release
Incident actions
=> [MANIFEST] Revert this morning's release

base/notify-celery-email-send-primary/celery-email-send-deployment.yaml, base/notify-celery-email-send-scalable/celery-email-send-deployment.yaml, base/notify-celery-email-send/celery-email-send-deployment.yaml, base/notify-celery-sms-send-primary/celery-sms-send-deployment.yaml, base/notify-celery-sms-send-scalable/celery-sms-send-deployment.yaml, base/notify-celery-sms-send/celery-sms-send-deployment.yaml
The new feature flag is [now used](https://github.com/cds-snc/notification-api/pull/2216) in code run by celery.
=> fix: use FF_TEMPLATE_CATEGORY in celery

helmfile/overrides/system/kube-state-metrics.yaml.gotmpl
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/398
Hopefully this will allow the namespace metrics to be exposed.
=> fix: allow metrics for namespaces

helmfile/overrides/system/kube-state-metrics.yaml.gotmpl
Reverts cds-snc/notification-manifests#2824
> "Let's see if this does what we want!"
It did not. 😞
=> Revert "fix: allow metrics for namespaces"

helmfile/overrides/system/kube-state-metrics.yaml.gotmpl
Reverts cds-snc/notification-manifests#2791
Let's see how much of Ben's work we can revert before he comes back. And this one might even fix the missing data in our dashboards!
=> Revert "Paring down kube state metrics"

env/staging/performance/celery-sms-send-scalable-hpa-patch.yaml
Investigating scaling up our SMS sending: bump up the max celery sms-send-scalable pods from 20 to 30.
=> bump up maxreplicas for sms in staging 20 -> 30

env/staging/performance/celery-sms-send-scalable-hpa-patch.yaml
Investigating scaling up our SMS sending: bump up the max celery sms-send-scalable pods from 30 to 40.
=> sms send scalable 30 -> 40

env/dev/admin-target-group.yaml, env/dev/api-target-group.yaml, env/dev/aws-auth-configmap.yaml, env/dev/document-download-api-target-group.yaml, env/dev/documentation-target-group.yaml, env/dev/kustomization.yaml
Dev only - I have hard-coded the target type in the target group bindings, and removed the aws-auth config map which is now managed by terraform for dev.
Dev was failing creation due to bad aws-auth configmap, and target group bindings being created too quickly.
=> Fixes for Dev

.github/workflows/merge_to_main_production.yaml
Functionality to clear the cache after production deploy completes! All the relevant secrets have already been added.
=> [MANIFEST] Added functionality to clear cache after prod deploy

.github/workflows/merge_to_main_staging.yaml
ERROR:
```
Invalid workflow file: .github/workflows/merge_to_main_staging.yaml#L135The workflow is not valid. .github/workflows/merge_to_main_staging.yaml (Line: 135, Col: 11): Input environment is required, but not provided while calling.
--
[Invalid workflow file: .github/workflows/merge_to_main_staging.yaml#L135](https://github.com/cds-snc/notification-manifests/actions/runs/10774286400/workflow)
The workflow is not valid. .github/workflows/merge_to_main_staging.yaml (Line: 135, Col: 11): Input environment is required, but not provided while calling.
```
Added the env variable to try and fix it.
=> [MANIFEST] added env variable

.github/workflows/helmfile_production_apply.yaml, .github/workflows/helmfile_production_plan.yaml, .github/workflows/helmfile_staging_apply.yaml, .github/workflows/helmfile_staging_apply_specific_app.yaml, .github/workflows/helmfile_staging_plan.yaml, .github/workflows/merge_to_main_production.yaml, .github/workflows/merge_to_main_staging.yaml, scripts/createVPNConfig.sh
Moving the auto generation of vpn config to a script and suppressing error outputs to be safe.
Part of VPN reconfig
=> Moving create vpn config to script

.github/workflows/ai-code-scanner.yml
Re-enable the code review bot but on push gh event
By using the `[review]` tag in a commit description, that will trigger the AI code review on the whole PR. Use it only once a PR is used in order to reduce call to the github actionand and costs $$$.
* …
=> Re-enabled the ai code review action via manual push trigger

env/staging/performance/celery-sms-send-scalable-hpa-patch.yaml
Set the `celery-sms-send-scalable-hpa` max pods to 27. This will give us 30 sms sending pods in total, which should send at a rate of around 5000 notifications per minute (which would be 10000 fragments / minute for our average of 2 fragments / sms in production).
We'll use this to test (using internal test numbers) what happens to the system if we try to send at this rate! 📈
=> set staging sms hpa to max 27

.github/workflows/helmfile_production_apply.yaml, .github/workflows/helmfile_production_plan.yaml, .github/workflows/helmfile_staging_apply.yaml, .github/workflows/helmfile_staging_apply_specific_app.yaml, .github/workflows/helmfile_staging_plan.yaml, .github/workflows/merge_to_main_production.yaml, .github/workflows/merge_to_main_staging.yaml, scripts/createVPNConfig.sh
The "old" way of deploying our Terraform code did not require the TFVars file when fetching outputs, but the new way does. This PR install 1Pass CLI on workflow runs and fetches the TFVars file.
Re: TF Environment variable consolidation
=> fix: VPN Config

base/notify-celery-email-send-primary/celery-email-send-deployment.yaml, base/notify-celery-email-send-scalable/celery-email-send-deployment.yaml, base/notify-celery-email-send/celery-email-send-deployment.yaml, base/notify-celery-main-primary/celery-deployment.yaml, base/notify-celery-main-scalable/celery-deployment.yaml, base/notify-celery-main/celery-deployment.yaml, base/notify-celery-other/celery-beat-deployment.yaml, base/notify-celery-other/celery-sms-deployment.yaml, base/notify-celery-sms-send-primary/celery-sms-send-deployment.yaml, base/notify-celery-sms-send-scalable/celery-sms-send-deployment.yaml, base/notify-celery-sms-send/celery-sms-send-deployment.yaml
`FF_ANNUAL_LIMIT` is exposed in celery.
=> Pass FF_ANNUAL_LIMIT to celery

base/notify-api/api-deployment.yaml
The newly added cypress secrets needed to also be added to the migrate-db init container. 
https://gcdigital.slack.com/archives/CV38DBNVA/p1731431934125009
=> Adding cypress secrets on migrate-db init container

base/notify-api/api-deployment.yaml
Increase the initial delay for liveness probe to 40s; give it a bit more room.
=> [MANIFEST] Increase the initial delay for liveness probe to 40s

.github/workflows/clear-notify-cache.yaml, .github/workflows/merge_to_main_production.yaml, .github/workflows/merge_to_main_staging.yaml, .github/workflows/smoke_test.yaml
Removing the smoke test secrets since they aren't secret. Also switching the smoke access key and access key secret to be the normal ones for staging. They would have been this anyway since there is only one access key/secret in staging AWS.
In preparation for cleaning up github secrets.
=> smoke test secrets removed

.github/workflows/clear-notify-cache.yaml, .github/workflows/merge_to_main_production.yaml, .github/workflows/merge_to_main_staging.yaml
Fixing clear cache job so that it works with non secret vals.
Github Secret Management
=> Clear Cache Fix

.github/workflows/smoke_test.yaml
smoke test is flakey, this increases the timeout.
=> increase smoke timeout

.github/workflows/helmfile_production_apply.yaml, .github/workflows/helmfile_production_plan.yaml, .github/workflows/helmfile_staging_apply.yaml, .github/workflows/helmfile_staging_apply_specific_app.yaml, .github/workflows/helmfile_staging_plan.yaml, .github/workflows/merge_to_main_staging.yaml
Switch to using the OP SA token secret that has the environment name in it
Also cleaning up kubeconfig code to use aliases instead of context renaming
Also Also normalizing the staging secret for aws account id
=> Removing non specific OP SA Token

helmfile/helmfile.yaml
The step label has been added to kube state metrics to make sure it gets applied in the helmfile apply's on a new environment.
Debugging the gerd derm dashboards in dev
=> Adding step label to kube state metrics

helmfile/charts/karpenter-nodepool/values.yaml, helmfile/charts/notify-document-download/values.yaml
Doc download is slow to launch on 3.12 w/ NR
Adding an initial delay of 30s to probes.
=> fix initial delay for dd

helmfile/charts/notify-celery/values.yaml, helmfile/overrides/notify/api.yaml.gotmpl, helmfile/overrides/notify/celery.yaml.gotmpl
Fixed dd api url everywhere it was specified.
=> Fixed dd api URL everywhere

env/dev/kustomization.yaml
Our weekend CRON job that recreates dev is still on Kustomize.  We need this to be turned on so that we our environment gets created properly until we adjust it to use Helm.
Just uncommenting some kustomize stuff for the dev environment
We are in the middle of a migration to Helmfile and this file was modified, but didn't need to be.
=> Turning Kustomize back on for DEV

.github/workflows/test_env_vars.yaml
When we removed staging from the test env vars job, I accidentally removed the production login instead of the staging.
Helm migration
=> Switching test env vars credentials to prod not staging

.github/workflows/smoke_test.yaml
api is now Python 3.12 so need to change smoke test GitHub action
Made the smoke test run (successfully) on this PR:
https://github.com/cds-snc/notification-manifests/actions/runs/12677958750/job/35334469080
(then switched back to only running on release branches)
=> fix: use Python 3.12 for smoke test

helmfile/charts/notify-api/templates/deployment.yaml, helmfile/charts/notify-api/values.yaml
Setting API initial delays to 45 seconds instead of 30/10 - lets see if that's enough.
API Timeouts
=> set probe timeoutes

.github/workflows/helmfile_production_plan.yaml, .github/workflows/helmfile_staging_plan.yaml
We were running a helmfile diff against staging on [AUTO-PR] and [MANIFEST] PRs which we don't want - we want prod diff on that.
Helmfile release
=> don't plan staging on prod release

helmfile/overrides/notify/celery.yaml.gotmpl
We're getting rate limit issues with sms while having kustomize and helmfile running celery sms. Scaling helmfile to 0.
=> [MANIFEST] Scale helmfile celery sms to 0

helmfile/overrides/notify/api.yaml.gotmpl, helmfile/overrides/notify/celery.yaml.gotmpl
Setting prod helmfile autoscaling to the same as kustomize
=> setting prod autoscaling to match kustomize

.github/workflows/smoke_test.yaml
Smoke test is timing out waiting for delivery receipts to be retried.
Here we bump up the timeout to larger than what would have been needed in the latest timeout.
=> fix: increase smoke test timeout

.github/workflows/smoke_test.yaml
* Enabled manual run of the smoke tests github action from the action pane.
We can run remotely on github actions, for a faster mean to run this instead of setting it up locally.
=> Enabled manual run of the smoke tests from the gh action pane

helmfile/overrides/notify/celery.yaml.gotmpl
This should be set to 1, not 3
=> reducing dedicated celery to 1

helmfile/charts/notify-celery/values.yaml
We're seeing pod eviction due to running out of memory on staging Nodes. Lets up the request to something higher so that K8s doesn't try and put too many celery pods on the same nodes.
Incident debugging
=> [MANIFEST] Upping celery memory requests to 800

helmfile/charts/notify-admin/values.yaml, helmfile/overrides/notify/admin.yaml.gotmpl
Remove the https prefix from documentation_domain
Bug introduced from helmfile migration
=> remove https from documentation domain

helmfile/overrides/notify/api.yaml.gotmpl, helmfile/overrides/notify/celery.yaml.gotmpl
Remove https from asset domain
Helmfile bug
=> [MANIFEST] remove https from asset domain

.github/workflows/autopr_merged.yaml, .github/workflows/update_image_tags_staging.yaml
Trying to fix branch protection which is failing on the workflows
Issues w/ helmfile migration
=> attempting to fix branch protection

.github/workflows/helmfile_staging_plan.yaml
We'll need to run staging diff even on prod-prs for the time being. I have an idea on how to fix this properly but it will require an overhaul of the workflows.
=> remove if condition on staging helmfile diff

helmfile/overrides/notify/admin.yaml.gotmpl, helmfile/overrides/notify/api.yaml.gotmpl, helmfile/overrides/notify/celery.yaml.gotmpl, helmfile/overrides/notify/document-download.yaml.gotmpl, helmfile/overrides/notify/documentation.yaml.gotmpl
The default latest seems to be behaving weirdly. Removing that.
=> [MANIFEST] Removing the default since it seems to not be working as expected

helmfile/overrides/notify/api.yaml.gotmpl, helmfile/overrides/notify/celery.yaml.gotmpl, helmfile/overrides/notify/document-download.yaml.gotmpl, helmfile/overrides/notify/documentation.yaml.gotmpl
Adding quotes around docker tags everywhere.
Bug in helm/helmfile that was ignoring docker tags
=> Adding quotes around docker tags

.github/workflows/merge_to_main_production.yaml
pr-bot isn't changing the api lambda tag, this PR does it manually. We will fix the pr-bot soon but there's recent bugfixes we should release asap.
=> [MANIFEST] manual release of api lambda to bb33743

env/production/kustomization.yaml
Fix indent causing ci failure.
=> [MANIFEST] Fix indent

helmfile/overrides/notify/admin.yaml.gotmpl
adding missing asset domain variable!
=> asdding back missing asset_domain variable

.github/workflows/helmfile_staging_apply.yaml, scripts/lambdaParamStoreUpdates.sh
removing some env vars from our param store because they are not needed and are creating duplicate keys
changing our workflow to no longer pull secrets from celery and DD. Also adding a timer to give helm 20 seconds to finish updating its secrets before we pull them for the parm store.
changing our workflow to no longer pull secrets from celery and DD. Also adding a timer to give helm 20 seconds to finish updating its secrets before we pull them for the parm store.
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/514
=> removing DD and Celery variables beacause of all the duplicates

helmfile/overrides/system/fluentbit-agent.yaml.gotmpl
Change the log group name to ${CLUSTER_NAME}
=> Parameterize cluster name in logs

helmfile/charts/notify-api/values.yaml, helmfile/overrides/notify/api.yaml.gotmpl
Adding FIDO2_DOMAIN variable to the API. This will fix some errors we have with yubikey and passkey for 2fa in production
FIDO2_DOMAIN: "dev.notification.cdssandbox.xyz" (setting this as required by environment)
https://docs.google.com/document/d/1055vlAcC2sXZCka1ogH7zU9QeJzASUhQuWJ_yGd3WPk/edit
=> [MANIFEST] FIX Adding FIDO2_DOMAIN Var to API

.github/workflows/helmfile_production_apply.yaml
The image tags to release to prod got left behind in #3577
=> [MANIFEST] add lambda images to prod helm apply

helmfile/overrides/system/fluentbit-agent.yaml.gotmpl
This will fix (for the most part) celery multiline issues. There are a couple outstanding oneoffs, but the main thing is that stack traces work now. 
Celery multiline on fluentbit
=> celery multiline

.github/workflows/helmfile_production_plan.yaml, .github/workflows/helmfile_staging_plan.yaml
This will hopefully prevent long helmfile diffs from crashing PRs.
=> Truncate long helmfile diffs

.github/workflows/helmfile_production_plan.yaml, .github/workflows/helmfile_staging_plan.yaml
When adding the logic to detect helmfile diff comments that were too long, I broke multi-line comments. This fixes that while keeping the too long logic.
=> Helmfile diff multiline fix

base/notify-system/kustomization.yaml
Removing the reference to the alb ingress controller in kustomize.yaml 
Still need the actual file for the migration.
This will not do anything in staging/prod since Kustomize doesn't delete resources.
=> removing reference to alb ingress controller for kustomize

helmfile/overrides/notify/celery.yaml.gotmpl
We set the sms-send hpa to go up to 6 pods, here we dial it back to 3 (same as prod and same as the original value speced out in September)
=> set staging and dev sms-send-scalable hpa back to max 3 pods

helmfile/helmfile.yaml
Moving cloudwatch agent to helmfile in prod.
Delete the cwagent yaml from kustomize in prod before merging.
=> Cloudwatch agent in prod

helmfile/overrides/notify/api.yaml.gotmpl
Min replicas on api has to be 2 so that the PDB works as expected (allows disruptions)
Failed K8s node upgrade
=> Setting min replicas for api to 2 so that we can disrupt

helmfile/charts/notify-database/templates/upgrade-database-job.yaml, helmfile/charts/notify-database/values.yaml
DB upgrade jobs will linger for 24 hours in case we want to easily debug the job.
helm configuration for the notify-database helm chart
We are running the DB upgrade in a K8s job now and we wanted to have the job linger for 24 hours after running.  This PR sets that configuration.
=> changing the job to linger for 24 hours

helmfile/charts/notify-api/templates/deployment.yaml, helmfile/overrides/notify/api.yaml.gotmpl
The K8s API Pod will no longer have the DB upgrade code run during its deployment.  This is now done in a separate step/pod prior to deploying the API.  The Lambda API and K8s API  deployments will both now be independent of the API K8s deployment.
Updating the API K8s deployment (Helmfile) file to remove the DB upgrade scripts.
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/20
=> Removing old DB Upgrade from Production API Pod

.github/workflows/db_production_upgrade_manual.yaml, .github/workflows/db_staging_upgrade_manual.yaml
Nothing, this will only run if manually triggered
Updates to our Github Workflows (adding two) for Prod and Staging to run the latest API tag DB upgrade script.
=> adding workflows to run latest db upgrade manually

helmfile/helmfile.yaml, helmfile/overrides/system/aws-lb-controller.yaml.gotmpl, helmfile/overrides/system/k8s-event-logger.yaml.gotmpl, helmfile/overrides/system/karpenter.yaml.gotmpl, helmfile/overrides/system/kube-state-metrics.yaml.gotmpl, helmfile/overrides/system/metrics-server.yaml.gotmpl
Trying to investigate the 504 gateway timeouts. I can sometimes correlate a node being recycled around the time the 504 appears. When we switched from Kustomize to Helmfile we didn't always add the node selector for system critical apps to be ON_DEMAND. Adding that here. Not 100% sure this will fix anything but it should be there anyway.
Investigating 504 errors in prod
=> adding node selectors to system critical apps

helmfile/charts/aws-cloudwatch/templates/cwagent-configmap.yaml
Cloudwatch agent config was breaking in prod due to additional comma.
Broken release
=> [MANIFEST] fix cw agent config for prod

helmfile/charts/notify-admin/templates/imagePullSecret.yaml, helmfile/charts/notify-admin/templates/serviceaccount.yaml, helmfile/charts/notify-api/templates/imagePullSecret.yaml, helmfile/charts/notify-api/templates/serviceaccount.yaml, helmfile/charts/notify-celery/templates/imagePullSecret.yaml, helmfile/charts/notify-celery/templates/serviceaccount.yaml, helmfile/charts/notify-document-download/templates/imagePullSecret.yaml, helmfile/charts/notify-document-download/templates/serviceaccount.yaml, helmfile/overrides/notify/admin.yaml.gotmpl, helmfile/overrides/notify/api.yaml.gotmpl, helmfile/overrides/notify/celery.yaml.gotmpl, helmfile/overrides/notify/document-download.yaml.gotmpl
I had the docker image pull secret in the wrong place and also screwed up the naming. All in all,  a complete failure on my part. I've verified this fixes it.
Docker 429 rate limit
=> Docker Image Pull Secrets Fix

.github/workflows/database_migration_staging_manual_pwprotected.yaml
This is a duplicate of the production equivalent of the data migration workflow, but happening in the staging environment. The code is the same except for references to the environment has been switched to staging. Only one production reference remains and …
=> Submitted a newly crafted github action to test the pw protected gh action workflow

.github/workflows/database_migration_production_manual.yaml
Nothing until this workflow is run.  When it's run it will now display a title that's more indicative of what the job is doing rather than the hardcoded "Downgrade" it had before.
adding a variable to the title of one of the workflow steps
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/558
=> Fixing Step Name from "Downgrade"

.github/workflows/helmfile_production_apply.yaml, .github/workflows/helmfile_staging_apply.yaml, helmfile/helmfile.yaml
Fixing CRDs for helmfile
Should just get our helmfile applies to work
updating helmfile (and the staging/production helmfile syncs in GHA) to install the CRDs first
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/568
=> Helmfile CRD Adjustments

.github/workflows/helmfile_production_apply.yaml, .github/workflows/helmfile_staging_apply.yaml
fixing duplicate step names in my workflows
Making helmfile apply work
=> Fixing Duplicate Step Names

.github/workflows/helmfile_staging_plan.yaml, helmfile/helmfile.yaml
We will try adding New Relic back to staging since it's working fine on dev 🤷 
Also add --context 2 to the helmfile diffs which will show only the changes and not the whole yaml.
New Relic debugging
=> Enable nr staging and shorten diff

helmfile/overrides/system/karpenter.yaml.gotmpl
When I implemented nidhogg on staging and dev, I forgot to wrap the startup taints on Karpenter nodes with an if statement so that they don't apply on prod. As it stands now, all of the nodes karpenter spins up are unusable in prod because these taints are never removed (since Nidhogg isn't in prod).
Nidhogg
=> [MANIFEST] remove startup taings on prod

helmfile/helmfile.yaml
New relic keeps intermittently failing on helmfile apply. Removing for now.
Adding new relic to EKS.
=> disable NR in staging

.github/workflows/helmfile_production_apply.yaml, .github/workflows/helmfile_staging_apply.yaml, helmfile/helmfile.yaml
Turning on New Relic K8s dashboards for staging, and updating our workflows to use apply rather than sync for helmfile (plus doing the crds in a step prior to everything else
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/568
=> Helmfile Apply Updates to fix CRDs and New Relic

helmfile/charts/karpenter-nodepool/templates/nodepool.yaml
Karpenter disruption config was in the wrong spot and wasn't taking effect. Fixed.
HPA and karpenter tuning
=> Fixing location of disruption

helmfile/overrides/system/karpenter.yaml.gotmpl, helmfile/overrides/system/newrelic.yaml.gotmpl
Staging karpenter will use new node sizes with a minimum of 4 vcpus to accommodate the additional CPU load we have with New Relic.
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/580
=> staging karpenter to new node sizes

.github/PULL_REQUEST_TEMPLATE.md
The changes to the notification-lambdas repo are now being populated correctly in the [release PRs](https://github.com/cds-snc/notification-manifests/pull/3871). This PR adds them to the checklist and adds links so that the OL can easily verify that the images exist.
=> Add notification-lambdas to pr template

helmfile/charts/notify-database/templates/_helpers.tpl, helmfile/charts/notify-database/templates/run-database-job.yaml, helmfile/charts/notify-database/templates/secretsproviderclass.yaml, helmfile/charts/notify-database/values.yaml
Ideally a new K8s secret will be added that is discretely used by the database helm job.
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/631
=> K8s/Helmfile Secrets Store for Database

helmfile/charts/notify-database/values.yaml
Bug fix so that DB job is referencing proper secret store
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/631
=> Updating database secret provider class name

helmfile/overrides/notify/database.yaml.gotmpl
Should fix the db upgrade so that it doesn't pull "latest" tagged image
=> fixing tag so it uses variable
