cds-snc/notification-manifests

env/production/kustomization.yaml

[AUTO-PR] Automatically generated new release 2021-01-19T15:24:12.570Z

---

env/production/kustomization.yaml

Almost done with French and English content there so releasing to production

Bump documentation in production

---

env/production/kustomization.yaml

ADMIN: 
- [python 3.9 upgrade (#889)](https://github.com/cds-snc/notification-admin/commit/c920b0968e221044e7c57bf6387e7a4e033d6344) by dorianjp
- [Improved platform compatibility (windows) (#892)](https://github.com/cds-snc/notification-admin/commit/978ccb34915a975a62ab771dd19348ed1da3852c) by Jimmy Royer 
API: 
- [Upgrade Python 3.9.1 plus celery 5x (#1209)](https://github.com/cds-snc/notification-api/commit/757e94bcec48347663d978e9bd10121f1eaf7b21) by dorianjp
- [fix: Improved platform compatibility (windows) (#1208)](https://github.com/cds-snc/notification-api/commit/79d01572b2cbb67b5a3d96a2c64875ea292a095a) by Jimmy Royer

[AUTO-PR] Automatically generated new release 2021-01-25T20:17:57.007Z

---

env/production/kustomization.yaml

ADMIN: 
- [Homepage content update (#894)](https://github.com/cds-snc/notification-admin/commit/ab3b8cafe4a90043018db41b9d4a6b1dc760522c) by Ren-David
- [feat: no identity step for logged in users (#895)](https://github.com/cds-snc/notification-admin/commit/4eb411a5d850de74685dbe7db12d897ffc2cda76) by Antoine Augusti
- [Improve password hint in account creation by being more descriptive (#896)](https://github.com/cds-snc/notification-admin/commit/0237926c01c58d72a927e85aba58bb5b80dd20e9) by Anik Brazeau
- [feat: move SMS senders to platform admin (#893)](https://github.com/cds-snc/notification-admin/commit/376c544d2e …

[AUTO-PR] Automatically generated new release 2021-02-01T13:38:09.704Z

---

env/production/kustomization.yaml

ADMIN: 
- [Tweaks to clean up "Create an account" page content (#897)](https://github.com/cds-snc/notification-admin/commit/ad1a7734f84492a085420ee052c243d9fb189adc) by Anik Brazeau 
API:

[AUTO-PR] Automatically generated new release 2021-02-01T15:06:19.597Z

---

env/production/kustomization.yaml

ADMIN: 
- [fix french on branding page (#906)](https://github.com/cds-snc/notification-admin/commit/dd0d0ffb7a57298ef871ce840d0ec135336f0223) by Anik Brazeau
- [change line of copy in service accounts (#900)](https://github.com/cds-snc/notification-admin/commit/77b46514791d6f2a83bdff69396e15e7f6c4f71c) by Anik Brazeau
- [swap button copy at top and bottom of page (#903)](https://github.com/cds-snc/notification-admin/commit/d58fc3bad5128c2a8612d2beba4ee4830d8eb7e3) by Anik Brazeau
- [fix: markdown for French documentation in README (#901)](https://github.com/cds-snc/notification-admin/commit/aa4999ddd33008141c4780350b519e54b24b4532) by David Larlet 
API: 
- [feat: add appropriate tags when creating a ticket on Freshdesk (#1222)](https://github.com/cds-snc/notification-api/commit/d33727f06da …

[AUTO-PR] Automatically generated new release 2021-02-04T13:20:25.794Z

---

env/production/kustomization.yaml

ADMIN: 
- [Dependency upgrade (#902)](https://github.com/cds-snc/notification-admin/commit/f9e44c7d06135341f1b53601575edad6c59a976b) by Ren-David
- [feat: add create an account on why notify (#909)](https://github.com/cds-snc/notification-admin/commit/de0d914e9e6596c8ad7b1f28db3c016d1ac41f72) by Antoine Augusti
- [feat: number format for notifications per day (#907)](https://github.com/cds-snc/notification-admin/commit/a44d616fe98b0fec7b48ef9438eb2462d9322361) by Antoine Augusti
- [feat: add links to documentation (#908)](https://github.com/cds-snc/notification-admin/commit/0a6ebee8ec992f8ab24a6e9b8de954279a11b614) …

[AUTO-PR] Automatically generated new release 2021-02-10T18:50:03.590Z

---

env/production/kustomization.yaml

Release https://github.com/cds-snc/notification-manifests/pull/252 to production

Bump production to 0.27.0

---

env/production/kustomization.yaml

Releasing https://github.com/cds-snc/notification-admin/pull/914 to production

Add nshealth.ca to gov domains

---

env/production/kustomization.yaml

ADMIN: 
API: 
- [feat: remove reply-to for Notify no reply emails (#1240)](https://github.com/cds-snc/notification-api/commit/2c369fdd1610311a0908735d53df0615e887bfd2) by Antoine Augusti
- [Improve docker notification-api launch time by moving pip install into the dockerfile (#1239)](https://github.com/cds-snc/notification-api/commit/a5837b1afbc6ca450f64a39c8f8537a99e5d0240) by Quan Nguyen
- [Fix test suite to run locally without errors as well as in the evening …

[AUTO-PR] Automatically generated new release 2021-03-01T15:12:31.084Z

---

env/production/kustomization.yaml

ADMIN: 
- [Update AWS CLI when building container (#918)](https://github.com/cds-snc/notification-admin/commit/f947e0d2053b372d2321670dcf7d0260287dba8d) by Antoine Augusti
- [Request to go live process in service settings (#915)](https://github.com/cds-snc/notification-admin/commit/da916aaab10f21284da0bc355448da72635fe3c7) by Antoine Augusti
- [feat: generate EN translations from FR file (#916)](https://github.com/cds-snc/notification-admin/commit/21ee0f497ca1670 …

[AUTO-PR] Automatically generated new release 2021-03-02T14:57:12.210Z

---

env/production/kustomization.yaml

- [Fix overnight tests tz failure (#1243)](https://github.com/cds-snc/notification-api/commit/0ede6a61b48289236d1873124965d2bc22a9b27b) by Quan Nguyen
- [fix: removed gov.uk from error message (#1241)](https://github.com/cds-snc/notification-api/commit/ed3926e98598bace6dac04d4ca964d5c6ecf2cbd) by Quan Nguyen
- [Fix alignment / padding for the "Why GC Notify" page (#921)](https://github.com/cds-snc/notification-admin/commit/d67d302202e9825a4e1d54f11213d293393fafad) by Anik Brazeau
- [hotfix: issue where 404 fails as 500 due to required context …

[AUTO-PR] Automatically generated new release 2021-03-04T18:19:14.322Z

---

env/production/kustomization.yaml

- [added prefixes for nav views to fix missing context on 404 (#923)](https://github.com/cds-snc/notification-admin/commit/ce8b8649984c28e7ddc0e2074cf89c368d746d40) by dorianjp

[AUTO-PR] Automatically generated new release 2021-03-05T19:11:36.063Z

---

env/production/kustomization.yaml

- [Trial report fix (#1246)](https://github.com/cds-snc/notification-api/commit/68e7059b611fb8181a8a831e21784ffb6fcc2002) by Ren-David
- [added cron schedule for after hours CI tests (#934)](https://github.com/cds-snc/notification-admin/commit/97978fd909e3cc02e6cca00d9a692c45dee19412) by dorianjp
- [Link fixes for nav on descender and bar underline  (#925)](https://github.com/cds-snc/notification-admin/commit/431b9975ae1219563a4f62425b62f77ad2083b50) by dorianjp
- [Tweak platform admin menu (#930)](https://github.com/cds-snc/notification-admin/commit/543f555a21e9024fd9889fecf2a6e45 …

[AUTO-PR] Automatically generated new release 2021-03-09T22:18:32.446Z

---

env/production/kustomization.yaml

- [Fix se connecter (#931)](https://github.com/cds-snc/notification-admin/commit/a4b3805f0c9b7bb6f8afab4e019326c508a38eb6) by dorianjp
- [fix containers header, content and footer for responsive padding (#932)](https://github.com/cds-snc/notification-admin/commit/30067937149b4d07aa2995607f1e674d92162419) by dorianjp
- [feat: enable customizing message limit when turning live (#935)](https://github.com/cds-snc/notification-admin/commit/50159428fcc4fd09475945589073dbf931cc0aa6) by Antoine Augusti
- [Added 'More' menu item when all items do not fit current resolution …

[AUTO-PR] Automatically generated new release 2021-03-10T22:46:30.580Z

---

env/production/kustomization.yaml

- [fix: display custom sending domain in settings if set (#943)](https://github.com/cds-snc/notification-admin/commit/fb726f60c238eac2597f79dbfbe8deb67bc80513) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-03-11T18:48:48.073Z

---

env/production/kustomization.yaml

- [fix: freskdesk subject needs to be friendly_support_type (#1251)](https://github.com/cds-snc/notification-api/commit/8410955e1596c93bbff4066e19d54ccddf0ca2d1) by Quan Nguyen
- [feat: pass filename argument when sending attachments (#1249)](https://github.com/cds-snc/notification-api/commit/b5139d4fcf5fd320e6311aa9a576435ac8d387be) by Antoine Augusti
- [Adding zendesk sell support (#1248)](https://github.com/cds-snc/notification-api/commit/1c5f0753c0332b6b8c68b99c3e6e01a2bb57d90b) by Quan Nguyen
- [Zen sell admin changes …

[AUTO-PR] Automatically generated new release 2021-03-17T15:13:28.018Z

---

env/production/kustomization.yaml

- [fix: adding hard coded source_id to a lead entry (#1253)](https://github.com/cds-snc/notification-api/commit/f6aaf23b48795206e9c347e7bf1af18b144fb8f2) by Quan Nguyen
- [feat: log iat value to ease debugging with JWT tokens (#1252)](https://github.com/cds-snc/notification-api/commit/8d4690fb09ddb132d64113fd1df250991c080d43) by Antoine Augusti
- [Content tweaks: rename activity dashboard + other copy consistency …

[AUTO-PR] Automatically generated new release 2021-03-22T16:52:16.069Z

---

env/production/kustomization.yaml

Releasing #326 to production as well
- [Offer reassurance in onboarding (#958)](https://github.com/cds-snc/notification-admin/commit/c110b4d455da0b641a28fe6337ab375ff468231f) by Anik Brazeau
- [feat: add ASCII art on homepage (#953)](https://github.com/cds-snc/notification-admin/commit/ab66b7d7b4e2edf134d308fcc8718439093897c2) by Antoine Augusti
- [Settings-related content tweaks (#963)](https://github.com/cds-snc/notification-admin/commit/5fb5 …

[AUTO-PR] Automatically generated new release 2021-03-24T14:52:55.448Z

---

env/production/kustomization.yaml

- [Shift the scheduler day forward when no time slots available on current day (#969)](https://github.com/cds-snc/notification-admin/commit/45e90a73e2a912c02222dd04e91563ea10655397) by Jimmy Royer
- [Shift account menu order (#956)](https://github.com/cds-snc/notification-admin/commit/ed7093f0c951f2d328bfc3c42aa7103f2d5ff8e0) by Anik Brazeau
- [fix: include base JS files when editing email template (#968)](https://github.com/cds-snc/notification-admin/commit/8dd2cc46d8981525760a3855761f8e7badd36634) by Antoine Augusti
- [typo (#966)](https://github.com/cds-snc/notification-admin/commit/cb123aa80c4a0efa1d945c466a1f2dbee80a4c6f) by Anik Brazeau

[AUTO-PR] Automatically generated new release 2021-03-25T14:47:37.032Z

---

env/production/kustomization.yaml

- [Better error messaging when blocked by Trial (#965)](https://github.com/cds-snc/notification-admin/commit/5b9a96164b3809336f1168d2623c8e276c11ee38) by Jimmy Royer
- [Clarify branding/language choice in service onboarding (#970)](https://github.com/cds-snc/notification-admin/commit/95dfe5eb479f7741b48f088368ac2f1d4835f011) by Anik Brazeau
- [Trial welcome screen (#967)](https://github.com/cds-snc/notification-admin/commit/0db88b57652d6f9f4bb99c9314c6f04d3943a210) by Ren-David

[AUTO-PR] Automatically generated new release 2021-03-30T14:09:30.270Z

---

env/production/kustomization.yaml

- [Adding zendesk create service integration (#1255)](https://github.com/cds-snc/notification-api/commit/be5ba9fc754ac6a9bfa2f52e55857fd00a6f17c1) by Quan Nguyen
- [Fix YAML indentation for Docker CI job (#973)](https://github.com/cds-snc/notification-admin/commit/701319186806794a8aaad41efbe69b7d6cebf5d3) by Antoine Augusti
- [feat: add a11y tracking to staging env (#972)](https://github.com/cds-snc/notification-admin/commit/aa8ed22e7c66c8f6297b495a47ca48a443ee4c66) by Max Neuvians
- [Displaying proper french plurals when failed messages exist (#971)](https://github.com/cds-snc/notification-admin/commit/8f89230483fd9c642951af9abe7945f0b231b064) by Ren-David …

[AUTO-PR] Automatically generated new release 2021-03-31T13:06:41.344Z

---

env/production/kustomization.yaml

- [added support for attachments on all files, personalisation valdiation (#1254)](https://github.com/cds-snc/notification-api/commit/c1483a339b7ee01d26ca02ecef19164b1219ce43) by dorianjp
- [Link or attachment api (#32)](https://github.com/cds-snc/notification-document-download-api/commit/eb2ea6a2f6a6bcbaa1bcb75922062415267324d9) by dorianjp
- [Document sending_method argument for files (#70)](https://github.com/cds-snc/notification-documentation/commit/d21ce0e8fd00ee8c41dcbab65e55a2ff13aa9525) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-04-06T12:04:13.029Z

---

env/production/kustomization.yaml

- [feat: delete daily limit cache when updating limits (#1258)](https://github.com/cds-snc/notification-api/commit/46f9ce23d0acc8ff52fb65fe96ac72ea3f5a40bc) by Antoine Augusti
- [feat: redirect to file directly (#52)](https://github.com/cds-snc/notification-document-download-frontend/commit/7f4f8dce6ac961eca19df62677320a0f471a7840) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-04-06T19:11:17.529Z

---

env/production/kustomization.yaml

- [Remove mention of interface for files sent as link (#73)](https://github.com/cds-snc/notification-documentation/commit/89abb9e10a2515965f50c70dc919eb11b5cfb733) by Anik Brazeau

[AUTO-PR] Automatically generated new release 2021-04-07T12:16:56.766Z

---

env/production/kustomization.yaml

- [feat: save stats for attachments (#1259)](https://github.com/cds-snc/notification-api/commit/595b6a11fbd74f33c407a78a42b3b886747ab05e) by Antoine Augusti
- [Use US Toll Free Number When Sending SMS Messages to the US (#1256)](https://github.com/cds-snc/notification-api/commit/55a002581858c9d03aecabadab5d1494cb0b19ad) by Ren-David
- [feat: add size and mime when uploading documents (#35)](https://github.com/cds-snc/notification-document-download-api/commit/ad3fd4dbdf241a226f7d69be585d511c91d2caf3) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-04-08T10:47:21.081Z

---

env/production/kustomization.yaml

- [fix: appropriate mime type for emails with attachments (#1260)](https://github.com/cds-snc/notification-api/commit/701a2f853dd4a5bb704321fca059b3ee79bdf5e7) by Antoine Augusti
- [Revert "Add conversion method for uploaded CSV files (#949)" (#977)](https://github.com/cds-snc/notification-admin/commit/946e1af5f9d5e88521f18bb09dfb9eb3559e50df) by Ren-David
- [feat: improve MIME detection for CSV files (#36)](https://github.com/cds-snc/notification-document-download-api/commit/785572e761e4a689303872a0e1e6205190be2191) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-04-08T19:20:09.923Z

---

env/production/kustomization.yaml

- [fix: display custom sending domain on email from page (#981)](https://github.com/cds-snc/notification-admin/commit/4c925d22fb5e7c98fdfee364bcf70b0dbdff91de) by Antoine Augusti
- [feat: let clients toggle their own attachments (#979)](https://github.com/cds-snc/notification-admin/commit/f165113b81e92585d58829f87de10d9c2de5d2d9) by Antoine Augusti
- [Request to go live pages display messages based on request status (#976)](https://github.com/cds-snc/notification-admin/commit/8788f660de9e8b3d38b8f8ec225732d1a3e6e707) by Jimmy Royer
- [feat: remove guidance on how to send files on templates page (#980)](https://github.com/cds-snc/notification-admin/commit/db203cf885a8846a7c3222350cc53d49eb5f727e) by Antoine Augusti
- [feat: allow - and _ in Notify email …

[AUTO-PR] Automatically generated new release 2021-04-12T13:34:36.088Z

---

env/production/kustomization.yaml

- [feat: add content-type header for direct attachments (#1263)](https://github.com/cds-snc/notification-api/commit/397b768ba76d72e6f44e95b34862021a22cf21ee) by Antoine Augusti
- [feat: write tests for AWS SES (#1261)](https://github.com/cds-snc/notification-api/commit/bbb0762e7eb89352f331c46974a8c813d230b4f3) by Antoine Augusti
- [feat: test html fragments for a11y issues (#974)](https://github.com/cds-snc/notification-admin/commit/7ed077e3b1be94529237a2198ed60d164992535c) by Max Neuvians
- [Change dash style for bulk UI …

[AUTO-PR] Automatically generated new release 2021-04-13T16:36:01.095Z

---

env/production/kustomization.yaml

- [feat: catch other exceptions for base64 decode (#1267)](https://github.com/cds-snc/notification-api/commit/c8a9fa05b278071148ef5a09cf9da299f253052a) by Antoine Augusti
- [feat: save provider response for tech failures on SNS (#1265)](https://github.com/cds-snc/notification-api/commit/d6ec50bb8f28007b8b7722f1be8607688a3224c2) by Antoine Augusti
- [Remove mention of Travis on healthcheck (#1264)](https://github.com/cds-snc/notification-api/commit/bc90b88e0058b521d723b321fa22c5a788cc5129) by Antoine Augusti
- [Change breaking spaces to nbsp for large french numbers (#992)](https://github.com/cds-snc/notification-admin/commit/43a991f524fb4aa74b8dd1ad9b6a956cea5753c0) by Ren-David
- [Remove mention of Travis on healthcheck …

[AUTO-PR] Automatically generated new release 2021-04-15T15:09:48.351Z

---

env/production/kustomization.yaml

- [feat: new StatsD metrics to compute SLOs (#1269)](https://github.com/cds-snc/notification-api/commit/2b0d16e899240ac40de6d1ba3e73cc596e374446) by Antoine Augusti
- [Bump utils to 43.5.0 (#1270)](https://github.com/cds-snc/notification-api/commit/8fcbeeb8f5a99e3ce184e06a0ff8acbb9c056587) by Antoine Augusti
- [feat: give warning to users when they are approaching sending limits (#1268)](https://github.com/cds-snc/notification-api/commit/614d4e8f49060efcd9b0ecca5229d5ad97237564) by Antoine Augusti
- [Go live to zendesk (#1266)](https://github.com/cds-snc/notification-api/commit/87c6b1a2e3816a8f99d73300cff6f76522582d14) by Quan Nguyen
- [feat: add bulk process type and route bulk notifications  (#1262)](https://github.com/cds-snc/notification-api/commit/e16420132ce2588c9769 …

[AUTO-PR] Automatically generated new release 2021-04-19T14:29:44.397Z

---

env/production/kustomization.yaml

- [fix: appropriate start date when recording stats for jobs (#1271)](https://github.com/cds-snc/notification-api/commit/05a8070997035fd493b8fd870a2441d5a1f5712b) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-04-19T17:34:50.869Z

---

env/production/kustomization.yaml

- [Bump notification-utils to 43.6.0 (#1272)](https://github.com/cds-snc/notification-api/commit/3c5350b0ec5719d7aa077cbd7811836d6faa8eac) by Antoine Augusti
- [Automated a11y test on authenticated dashboard page (#994)](https://github.com/cds-snc/notification-admin/commit/25710ef09d2cf0de5a9904c7ce76acb8657dcf4e) by Jimmy Royer
- [feat: clarify limits documentation (#78)](https://github.com/cds-snc/notification-documentation/commit/13fa7875757b3915c00ab8517f5614c33b5603c3) by …

[AUTO-PR] Automatically generated new release 2021-04-20T15:59:45.795Z

---

env/production/kustomization.yaml

- [fix: using update as the behaviour of contact/upsert is not reliable in the contact_id case (#1274)](https://github.com/cds-snc/notification-api/commit/2098439eafd8ec268553b1b7f0fbbc0d54b376df) by Quan Nguyen
- [Lead to contact (#1273)](https://github.com/cds-snc/notification-api/commit/d28dcb34e6b94a9ce0b0208a2d18a6163b3a5b71) by Quan Nguyen
- [feat: add years switches for months and templates (#996)](https://github.com/cds-snc/notification-admin/commit/09c63b4f5e8cc7ac217a3ca50b86d9458dbaccd0) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-04-21T16:33:35.387Z

---

env/production/kustomization.yaml

- [feat: add new error messages for SES (#1275)](https://github.com/cds-snc/notification-api/commit/5dba28060ef008792f19f4b515977633902858ed) by Antoine Augusti
- [feat: add new email error messages (#998)](https://github.com/cds-snc/notification-admin/commit/eb658e1766b57c938385667c4f3385a1a9f4a35c) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-04-22T17:57:23.816Z

---

env/production/kustomization.yaml

- [fix: adjust log level when email address is invalid (#1277)](https://github.com/cds-snc/notification-api/commit/dfc4fa9342f7c804ccb641c840316bb95d591ccc) by Antoine Augusti
- [feat: add tests when generating callbacks (#1276)](https://github.com/cds-snc/notification-api/commit/a42942bb59a13cbdba074f5f380cd5d50e340d38) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-04-23T15:13:36.446Z

---

env/production/kustomization.yaml

- [feat: queue callbacks for technical failures (#1278)](https://github.com/cds-snc/notification-api/commit/0161b006f9b8afc2499d254deea6838c7071d145) by Antoine Augusti
- [feat: set cache headers for static assets (#999)](https://github.com/cds-snc/notification-admin/commit/d7d7b59c8082d2017aebcf09a2b4f2c34d64dbb5) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-04-26T13:43:26.076Z

---

env/production/kustomization.yaml

- [fix: allow resetting password if using Fido keys (#1000)](https://github.com/cds-snc/notification-admin/commit/af89c0453256907f6e1af1555fd0dc4715d1db25) by Antoine Augusti
- [Better a11y focus / highlight on header (#997)](https://github.com/cds-snc/notification-admin/commit/6692caf94bb12a9ecae6b1376b942bcdd596227f) by Jimmy Royer
- [fix: don't go over the last possible time for scheduler (#1003)](https://github.com/cds-snc/notification-admin/commit/97c59815120e6ae72c60c10b06aba8c69c3bc294) by Antoine Augusti …

[AUTO-PR] Automatically generated new release 2021-04-27T14:02:26.741Z

---

env/production/cwagent-fluentd-quickstart.yaml

Same thing than https://github.com/cds-snc/notification-manifests/pull/422 but in production

feat: collect StatsD metrics more often

---

env/production/kustomization.yaml

- [feat: remove SMTP (#1279)](https://github.com/cds-snc/notification-api/commit/90d5cafa1b23f57727d80fe9bc686fc7c6dd5880) by Antoine Augusti
- [feat: remove SMTP pages (#1001)](https://github.com/cds-snc/notification-admin/commit/99091bd64c6a07a6e2497ccb8daa6caa41ee960b) by Antoine Augusti
- [fix: include image in nav menu item (#1006)](https://github.com/cds-snc/notification-admin/commit/b5f2fd111229d872f62dd93228d1ef8e94a2fd …

[AUTO-PR] Automatically generated new release 2021-04-27T19:47:40.185Z

---

env/production/kustomization.yaml

- [feat: handle invalid iat value for JWT tokens (#1280)](https://github.com/cds-snc/notification-api/commit/a24e5310dcf5b97f2e8e06ea8c7c26efccfdb3c0) by Antoine Augusti
- [Better a11y focus / highlight on home screen (#1004)](https://github.com/cds-snc/notification-admin/commit/1edd76782d5bcb57918354136024bf0eadf2f6d2) by Jimmy Royer

[AUTO-PR] Automatically generated new release 2021-04-29T12:04:05.526Z

---

env/production/kustomization.yaml

- [Better a11y focus / highlight on footer (#1007)](https://github.com/cds-snc/notification-admin/commit/6c7a0503364d45a4b18d1e8bf278c5200d3135cf) by Jimmy Royer

[AUTO-PR] Automatically generated new release 2021-04-29T13:27:02.557Z

---

env/production/kustomization.yaml

- [Bump utils to 43.7.0 (#1282)](https://github.com/cds-snc/notification-api/commit/dc20d5ae4d9c23b4aa24f8512e54e080a56b6132) by Antoine Augusti
- [feat: Underline on hover for footer links (#1009)](https://github.com/cds-snc/notification-admin/commit/6bb5c993833aaac73304b77a9180045f8929245b) by Jimmy Royer

[AUTO-PR] Automatically generated new release 2021-04-29T18:17:11.049Z

---

env/production/kustomization.yaml

- [fix: deal upsert was too specific (#1284)](https://github.com/cds-snc/notification-api/commit/0ebdfd5c542bf74ad6c14566cedb9b6dbbeadf7b) by Quan Nguyen
- [Zendesk go live notes (#1281)](https://github.com/cds-snc/notification-api/commit/f0f756d4078aff11fd72c481a3165ea9f329efe9) by Quan Nguyen
- [feat: opt out of Google FLoC (#1010)](https://github.com/cds-snc/notification-admin/commit/3cb78b27f18386525f96be786b68e6d049ebe5d5) by Antoine Augusti
- [feat: admin changes for go live request (#1008)](https://github.com/cds-snc/notification-admin/commit/5ab001196e764db186b4130d2bf51a77 …

[AUTO-PR] Automatically generated new release 2021-04-30T18:57:54.830Z

---

env/production/kustomization.yaml

- [Explicitly define alpine 3.13 in docker file (#1286)](https://github.com/cds-snc/notification-api/commit/ed6d869f29914df7d7ab9ffe081b18a2b1944205) by Jimmy Royer
- [fix: update pip in Dockerfile (#1285)](https://github.com/cds-snc/notification-api/commit/54c94f229b68b1d2577ab6ae9f46f463e5517e64) by Antoine Augusti
- [Bump dependencies (#1283)](https://github.com/cds-snc/notification-api/commit/2c8e2d2bfbd9c1c9c3da76606bf41dd131f85198) by Antoine Augusti
- [fix: rework logic for email 2FA logic once a month (#1016)](https://github.com/cds-snc/notification-admin/commit/17fdffc716d …

[AUTO-PR] Automatically generated new release 2021-05-04T11:53:52.338Z

---

env/production/kustomization.yaml

- [Bump utils to 43.9.0: bold, italic and h2 (#1288)](https://github.com/cds-snc/notification-api/commit/ab310f5f262eda136ba08ef9606d34501ae5e77a) by Antoine Augusti
- [Clean up message delivery status page with new failure reasons (#1024)](https://github.com/cds-snc/notification-admin/commit/12490313d0c367830898168e66d61c46e1a77cfa) by Anik Brazeau
- [feat: utils to 43.9.0, add bold, italic and h2 (#1017)](https://github.com/cds-snc/notification-admin/commit/e2eccc53a53f0e814d1ddfccf692add3ed32c481) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-05-11T15:06:36.896Z

---

env/production/kustomization.yaml

- [feat: split daily limit errors according to service type (#1292)](https://github.com/cds-snc/notification-api/commit/1997ebbee52a63f28f0d73771e832ef5df8f652c) by Antoine Augusti
- [feat: process multiple SES receipts if needed (#1295)](https://github.com/cds-snc/notification-api/commit/de3d4dfdb66a8e934fb751ad8a2e886f649a32a9) by Antoine Augusti
- [Fix some content focus states (#1018)](https://github.com/cds-snc/notification-admin/commit/d6e7b9f62a5242546263579cfd2e106aa3b231fb) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-05-12T13:12:05.054Z

---

env/production/kustomization.yaml

- [feat: remove Sendgrid as an email provider (#1291)](https://github.com/cds-snc/notification-api/commit/a431ead8c78fef1c096b6674f1d930c8a84a6cbc) by Antoine Augusti
- [feat: delete user cache when validating Fido key (#1025)](https://github.com/cds-snc/notification-admin/commit/7895d404b378970c7e8c4e98303d9fb772066f3c) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-05-13T17:08:54.660Z

---

env/production/kustomization.yaml

- [Bump utils to 43.9.1 (#1297)](https://github.com/cds-snc/notification-api/commit/161a365f5c5b1f4f5e6589162a607560e41b8ee3) by Antoine Augusti
- [Bump utils to 43.9.1 (#1027)](https://github.com/cds-snc/notification-admin/commit/f43ca84aa48e46d885e18f2de73f2d514d82ff3e) by Antoine Augusti
- [feat: add flash message when updating service settings (#1031)](https://github.com/cds-snc/notification-admin/commit/c24340f576d456cc7ffd65b458f10da26b88aa90) by Antoine Augusti
- [feat: improve exception message on contact form (#1028)](https://github.com/cds-snc/notification-admin/commit/017f4742f18eeaac486b3b90af3c4fe47c3ce02b) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-05-18T18:57:39.262Z

---

env/production/kustomization.yaml

- [fix: update service before sending notifications (#1299)](https://github.com/cds-snc/notification-api/commit/cbf069ffb7e59473484c9f0fcfa66471520bcb52) by Antoine Augusti
- [typo intented (#1034)](https://github.com/cds-snc/notification-admin/commit/e8e046eb14128a6f472351eb1a98697e6523ab74) by Anik Brazeau

[AUTO-PR] Automatically generated new release 2021-05-20T18:01:41.484Z

---

env/production/kustomization.yaml

- [Templates design updates (#1026)](https://github.com/cds-snc/notification-admin/commit/de9b82f9a89055bba713a30e923afa8eae6bbba2) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-05-26T11:55:56.846Z

---

env/production/kustomization.yaml

- [fix: Align search box with button (#1037)](https://github.com/cds-snc/notification-admin/commit/dc9ec6d0894b8ea8706e20faebf285f6136b55ba) by Jimmy Royer
- [Move Ready to send heading (#1039)](https://github.com/cds-snc/notification-admin/commit/60ca122299296fb56b80e86db6ae81bf45546b99) by Antoine Augusti
- [feat: full width for stick at bottom containers (#1036)](https://github.com/cds-snc/notification-admin/commit/02fc35583a4aaff198052fbf353c0f5e11db42e4) by Antoine Augusti
- [Improve aria attributes for menu items (#1035)](https://github.com/cds-snc/notification-admin/commit/c …

[AUTO-PR] Automatically generated new release 2021-05-26T21:20:28.193Z

---

env/production/kustomization.yaml

- [Small content fixes (#1041)](https://github.com/cds-snc/notification-admin/commit/3d7bcebf968dd078ca0f7977e38217511c879bce) by Anik Brazeau

[AUTO-PR] Automatically generated new release 2021-05-27T18:59:59.569Z

---

env/production/kustomization.yaml

- [feat: display attachments on notification page (#1044)](https://github.com/cds-snc/notification-admin/commit/b349cd981c6d917bf0c314eafc560c97a296c6ad) by Antoine Augusti
- [feat: adjust padding left for stick at bottom (#1042)](https://github.com/cds-snc/notification-admin/commit/569f4d781fe6e9df059114350519a93b840e314a) by Antoine Augusti
- [Make the request to go live form less confusing (#1040)](https://github.com/cds-snc/notification-admin/commit/eb1b368431623c8374a364726029b2c09a3cb3ec) by Stephen McMurtry

[AUTO-PR] Automatically generated new release 2021-05-31T13:25:37.290Z

---

env/production/kustomization.yaml

- [Bump utils to 43.11.0 (#1300)](https://github.com/cds-snc/notification-api/commit/2b1747d4f1797a7176bf28853c9ddc58fdad4d27) by Antoine Augusti
- [feat: use utils tag instead of hash for 43.11.0 (#1046)](https://github.com/cds-snc/notification-admin/commit/fd03bae337c76e319325a3fb5aa12ba79ec583fe) by Antoine Augusti
- [Bump utils to 43.11.0 (#1043)](https://github.com/cds-snc/notification-admin/commit/474916b5cfab6467f801673663cbc4655699fd29) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-05-31T18:35:42.839Z

---

env/production/kustomization.yaml

- [fix: set NOTIFY_ENVIRONMENT in staging (#1302)](https://github.com/cds-snc/notification-api/commit/20867e27afe9387072ac7019f87e0b8d94d8f657) by Antoine Augusti
- [feat: add staging environment in config (#1301)](https://github.com/cds-snc/notification-api/commit/470a39799f38021b3865ba0d77852b8eb3843deb) by Antoine Augusti
- [fix: set NOTIFY_ENVIRONMENT in staging (#1050)](https://github.com/cds-snc/notification-admin/commit/ …

[AUTO-PR] Automatically generated new release 2021-06-02T13:38:29.294Z

---

env/production/kustomization.yaml

- [Split formatting guide into multiple pages (#1051)](https://github.com/cds-snc/notification-admin/commit/3687e678558917f1d4e1fe6cb5373b88fb197088) by Antoine Augusti

[AUTO-PR] Automatically generated new release 2021-06-03T13:35:34.349Z

---

env/production/kustomization.yaml

- [fix: always route SMS to throttled queue when sender is set (#1308)](https://github.com/cds-snc/notification-api/commit/2a069d5da88e3635f949f3a3fa5de4adcf7ff3b0) by Antoine Augusti
- [Bump utils to 43.11.1 (#1306)](https://github.com/cds-snc/notification-api/commit/2d03645bb8144ac708aa9bbeca1eb0091cb9fdc8) by Antoine Augusti
- [fix: appropriate status for sms in reports (#1307)](https://github.com/cds-snc/notification-api/commit/026492f1119881cd4931edd31602897879e63d92) by Antoine Augusti
- [Run black on codebase (#1303)](https://github.com/cds-snc/notification-api/commit/bebd806cad9581101e5cc1d52db2613c1baa1fa9) by Antoine Augusti
- [New "create template" page (#1047)](https://github.com/cds-snc/notification-admin/commit/04640f1f1910a67b97ef8d86a0134 …

[AUTO-PR] Automatically generated new release 2021-06-05T13:44:54.325Z

---

env/production/kustomization.yaml

- [Stress tests basic scenario in JMeter and Locust (#1304)](https://github.com/cds-snc/notification-api/commit/14fc8db0c58dc22b3fb13cf91ad383b1897930a3) by Jimmy Royer
- [Switched all the remaining instances of govuk blue to the new blue (#1058)](https://github.com/cds-snc/notification-admin/commit/6d13d9f226db92d5a8b3855da1405a3faf9203a4) by Stephen McMurtry
- [Experiment: Adding MyPy …

[AUTO-PR] Automatically generated new release 2021-06-08T16:21:10.054Z

---

env/production/kustomization.yaml

- [fixed button style regressions (#1061)](https://github.com/cds-snc/notification-admin/commit/15d01d08e8336063768bbe507f554c2eb11ee094) by Stephen McMurtry
- [Made the default button colour blue (#1060)](https://github.com/cds-snc/notification-admin/commit/fabc2a7b35fd43aed9776127b16d5862fe7cdf0a) by Stephen McMurtry
- [Tweaks to team member permission content (#1053)](https://github.com/cds-snc/notification-admin/commit/9f799673d41572314a094fa409f57f5a7163c659) by Anik Brazeau

[AUTO-PR] Automatically generated new release 2021-06-09T18:37:22.517Z

---

env/production/kustomization.yaml

- [Adding the "write" link to the dashboard (#1059)](https://github.com/cds-snc/notification-admin/commit/c5123c20f2b5648992dac5fe535517b414820ebc) by Stephen McMurtry

[AUTO-PR] Automatically generated new release 2021-06-09T20:40:25.465Z

---

env/production/kustomization.yaml

- [Add the send button to dashboard, linked to a "sending" view of the templates page (#1062)](https://github.com/cds-snc/notification-admin/commit/0712fc671da5a0fc61ecd9f8710c67918c5fb770) by Stephen McMurtry

[AUTO-PR] Automatically generated new release 2021-06-10T19:34:27.701Z

---

env/production/kustomization.yaml

- [fix: Mute sms research mode error on callback (#1310)](https://github.com/cds-snc/notification-api/commit/da95d4d7620a05375fd7cb1a4931cf15ccd16f7a) by Jimmy Royer

[AUTO-PR] Automatically generated new release 2021-06-11T19:50:24.295Z

---

env/production/kustomization.yaml

- [API bulk sending (#1305)](https://github.com/cds-snc/notification-api/commit/ab6e86f452e00b84e28388633ad2da30819cda3a) by Antoine Augusti
- [Rework JMeter stress tests and renamed folder (#1309)](https://github.com/cds-snc/notification-api/commit/1ebc1e7f66b879866d2788e5531b77e8cf48ec5c) by Jimmy Royer
- [Sending view: Fixed a nav bug, fixed view with 0 templates (#1065)](https://github.com/cds-snc/notification-admin/commit/ec6f632e6900124f8d387e81bde72ed991251d9d) by Stephen McMurtry
- [fix: Regression bug cause active menu display to not show …

[AUTO-PR] Automatically generated new release 2021-06-14T18:18:27.204Z

---

env/production/kustomization.yaml

- [Fix sender ID for bulk API (#1312)](https://github.com/cds-snc/notification-api/commit/83df1e6fae359cadf7d28645b5b0148524de3b26) by Antoine Augusti
- [Rework content on view job page (#1070)](https://github.com/cds-snc/notification-admin/commit/7cf1712b0c88b771264d560df91f38144881e8a5) by Antoine Augusti
- [Update jobs to include bulk sends from the API (#1066)](https://github.com/cds-snc/notification-admin/commit/3c6e1e3a4744fb8baaf56caae56baf9060eb936c) by Antoine Augusti
- [fix: include sending view in templates pill links (#1068)](https://github.com/cds-snc/notification-admin/commit/f1343f0414 …

[AUTO-PR] Automatically generated new release 2021-06-22T14:27:55.829Z

---

env/production/kustomization.yaml

- [Fix/api auth error message (#1313)](https://github.com/cds-snc/notification-api/commit/cc380d90ca75c834fabbacccc2a28eda999aeade) by Omar Nasr

[AUTO-PR] Automatically generated new release 2021-06-23T15:40:56.737Z

---

.github/CODEOWNERS

Removing Antoine as a code owner and adding my github account ID.

Update code owner on the project.

---

.github/workflows/merge_to_main_production.yaml
env/production/kustomization.yaml

- [Just use start of gitsha for the lambda image tags (#1399)](https://github.com/cds-snc/notification-api/commit/8b33d6ec6a54525086d37f942295d05b4b624e1f) by Steve Astels
- [adding the aria-required attributes to textbox component (#1195)](https://github.com/cds-snc/notification-admin/commit/8afe9e53aa34089b81f6052d0bd3a821a62aa0a0) by Philippe Caron
- [Fix: contact helpful errors …

TEST [AUTO-PR] Automatically generated new release 2021-11-22T18:01:20.485Z

---

.github/workflows/merge_to_main_production.yaml
env/production/kustomization.yaml

- [Print out performance test result in html (#1407)](https://github.com/cds-snc/notification-api/commit/60774a21d70a46c01e18ee5f1d2273ea45a7f4f7) by Ikenna
- [pass tests locally and remotely (#1405)](https://github.com/cds-snc/notification-api/commit/c893f3896a66d9ae53b9b1f6df967f225508236e) by Steve Astels
- [timeout jobs after 2 hours rather than 1 (#1402)](https://github.com/cds-snc/notification-api/commit/6f71d29a8c60dcadee9562ea624d0c34171a …

TEST [AUTO-PR] Automatically generated new release 2021-11-25T21:19:44.233Z

---

.github/PULL_REQUEST_TEMPLATE.md

Thought it'd be good to add more details around doing a release. Thoughts?

Add a bit more to release PR template

---

env/staging/cwagent-fluentd-quickstart.yaml

Custom cloudwatch metrics in the embedded metrics format (EMF) will be used to provide instrumentation and Monitoring for Batch Saving. This PR enables the cloudwatch agent to monitor for EMF formatted log entries and to create the appropriate metrics in Cloudwatch.

feat: enable support for custom Cloudwatch embedded metrics

---

.github/workflows/sync_secrets_production.yaml
.github/workflows/sync_secrets_staging.yaml

Update workflow name to reflect migration to parameter store.

chore: update workflow name to reference parameter store

---

base/celery-deployment.yaml
base/celery-sms-deployment.yaml

Add the feature flag in the celery workers.

add feature flag

---

.github/workflows/merge_to_main_production.yaml
env/production/kustomization.yaml

Reverts cds-snc/notification-manifests#1174

Revert "[AUTO-PR] Automatically generated new release 2022-07-20T12:18:37.794Z"

---

.github/workflows/merge_to_main_production.yaml
.github/workflows/merge_to_main_staging.yaml
.github/workflows/s3-backup.yml

Add an alert to slack if the GitHub actions fail

add slack alert for failing github actions

---

env/production/kustomization.yaml

[MANIFEST] updating kube to remove bulk changes

---

base/api-deployment.yaml
base/celery-beat-deployment.yaml
base/celery-deployment-fargate.yaml
base/celery-deployment.yaml
base/celery-sms-deployment.yaml
env/production/kustomization.yaml
env/staging/kustomization.yaml

Release this first to staging with the `fix:` prefix.

fix: Add `FF_BOUNCE_RATE_BACKEND` to yaml files

---

env/staging/fluentbit.yaml

Reverting the fluent bit breaking changes in staging since we are done troubleshooting for today.

Reverting break testing changes for fluent bit

---

env/staging/replica_count.yaml

Reverts cds-snc/notification-manifests#1902

Revert "Staging celery worker incraese"

---

env/staging/replica_count.yaml

80 was putting us over the AWS limit and we had 24 emails that took a long time to come back as delivered (ie several minutes after everything else was done)
Let's see if 73 gives us around 90% of our AWS limit (5400 per minute out of limit 6000)

set staging celery maxReplicas to 73

---

env/scratch/fluentbit.yaml
env/staging/fluentbit.yaml

This will revert the attempted MLP fix that we tested in staging. It was unsuccessful.
Re: Fluentbit Not parsing Celery logs

reverting single MLP pipeline for staging and scratch

---

base-karpenter/karpenter/templates/namespace.yaml
base-karpenter/kustomization.yaml

Explicitly creating the namespace for karpenter

Adding kustomize namespace

---

base/celery-deployment.yaml

Missed a reference to karpenter on celery. Removing reference.

Missed one reference to karpenter

---

env/staging/performance.yaml

Staging celery maxreplicas to 73

---

base-karpenter/karpenter/provisioners/default.yaml
env/staging/karpenter.yaml

Karpenter will no longer try to consolidate pods onto smaller instances in staging.
Re: Performance tuning

Disabling consolidation to see if this reduces the killing of nodes 

---

base-karpenter/karpenter/provisioners/default.yaml
env/staging/karpenter.yaml

Karpenter ttl node 300s

---

base/notify-admin/admin-deployment.yaml
base/notify-celery/celery-beat-deployment.yaml
base/notify-celery/celery-deployment.yaml
base/notify-celery/celery-sms-deployment.yaml
base/notify-celery/celery-sms-send-deployment.yaml
base/notify-document-download/document-download-api-deployment.yaml
base/notify-documentation/documentation-deployment.yaml
env/production/kustomization.yaml
env/production/node-selector-patch.yaml
env/scratch/kustomization.yaml
env/scratch/node-selector-patch.yaml
env/staging/kustomization.yaml
env/staging/node-selector-patch.yaml

Celery SMS, Email, and the k8s notify api (not used at the moment) will deploy to spot instances via karpenter in staging.
Re: Performance tuning

Prepping kustomize for karpenter and configurable node selection

---

env/production/node-selector-patch.yaml

Both email and sms send celery will use karpenter nodes.
Performance tuning

setting prod celeries to use karpenter nodes

---

env/production/cwagent.yaml
env/scratch/cwagent.yaml
env/staging/cwagent.yaml

Setting the cwagent daemonset to be node critical priority.
Re: Node autoscaling

Setting cwagent daemonset priority

---

base/notify-celery-email-send/celery-email-send-deployment.yaml
base/notify-celery-email-send/celery-email-send-hpa.yaml
base/notify-celery-email-send/celery-email-send-service.yaml
base/notify-celery-email-send/kustomization.yaml
base/notify-celery-main/celery-beat-deployment.yaml
base/notify-celery-main/celery-deployment-fargate.yaml
base/notify-celery-main/celery-deployment.yaml
base/notify-celery-main/celery-hpa.yaml
base/notify-celery-main/celery-service.yaml
base/notify-celery-main/celery-sms-deployment.yaml
base/notify-celery-main/celery-sms-service.yaml
base/notify-celery-main/kustomization.yaml
base/notify-celery-sms-send/celery-sms-send-deployment.yaml
base/notify-celery-sms-send/celery-sms-send-hpa.yaml
base/notify-celery-sms-send/celery-sms-send-service.yaml
base/notify-celery-sms-send/kustomization.yaml
env/dev/kustomization.yaml
env/dev/node-selector-patch.yaml
env/dev/performance.yaml
env/staging/kustomization.yaml
env/staging/node-selector-patch.yaml
env/staging/performance.yaml

Reverts cds-snc/notification-manifests#2122
I think I fixed the problem [here](https://github.com/cds-snc/notification-api/pull/2012).

Revert "Revert "feat: Celery email send pods in staging""

---

env/staging/fluentbit.yaml

Fixing mem buff limit location

Moving mem buff limit to right place

---

env/staging/fluentbit.yaml

Fixing the name of the test init container.

Fixing init container name

---

env/staging/fluentbit.yaml

Staging fluent bit settings reverted to try and replicate paused tail and emitter

Resetting mem buff limits on fluent-bit to try and replicate errors

---

env/staging/fluentbit.yaml

Putting the upgraded memory buffer limits again!

Putting membuff limit back

---

base/notify-celery-email-send/celery-email-send-pdb.yaml
base/notify-celery-email-send/kustomization.yaml
base/notify-celery-main/celery-main-pdb.yaml
base/notify-celery-main/kustomization.yaml
base/notify-celery-sms-send/celery-sms-send-pdb.yaml
base/notify-celery-sms-send/kustomization.yaml

We will set pod disruption budgets for celery to try and make sure that we don't bring down all pods at once
Re: Incident - sms pods going to 0

[MANIFEST] Adding disruption budgets for celery

---

base/notify-celery-email-send/celery-email-send-deployment.yaml
base/notify-celery-main/celery-deployment.yaml
base/notify-celery-sms-send/celery-sms-send-deployment.yaml

Reverts cds-snc/notification-manifests#2197

Revert "Moving cwagent check outside of celery"

---

env/staging/node-selector-patch.yaml

Missed the last line from copy/paste

DD API Node Affinity Fix - Staging

---

helmfile/scratchContext.sh

An old scratch context script was accidentally included, which had a hard-coded (but not active) password for grafana in my scratch account. Removing.

Removing old scratch context

---

env/staging/performance.yaml

Revert staging perf

---

env/dev/aws-auth-configmap.yaml
env/production/aws-auth-configmap.yaml
env/staging/aws-auth-configmap.yaml

Wait for this PR prior to merge this one:
https://github.com/cds-snc/aft-account-request/pull/162
This will create the necessary OIDC roles within each GCNotify AWS accounts for dev, staging and production. We need to confirm what's the names of these roles then with the changes contained in this PR.
- Alternatively, change the [VERSION file](https://github.com/cds-snc/notification-manifests/blob/main/VERSION) - this will not create a new tag, but rather will release the …

[MANIFEST] Adding ipv4 oidc role to k8s map roles

---

helmfile/helmfile.yaml
helmfile/overrides/system/nginx.yaml.gotmpl
helmfile/overrides/tools/blazer.yaml.gotmpl

We will deploy a blazer instance into Kubernetes, and it will be accessible by:
https://blazer.staging.notification.internal/
This does not remove the existing blazer ECS!
VPN Tools

Blazer almost fully working in dev

---

.github/workflows/rollout-k8s-staging.yaml

A manually triggered rollout workflow should launch.
Working on private EKS

Testing a rollout workflow

---

.github/workflows/merge_to_main_production.yaml
env/production/kustomization.yaml

Reverts cds-snc/notification-manifests#2411

[MANIFEST] Revert #2411

---

.github/workflows/rollout-k8s-staging.yaml

K8s Rollout Workflow take 2
I'm testing the remote launch and passing the docker_sha as input, hence why I've commented everything else out - I just want to see that the value gets accepted

Deploy workflow tuning

---

.github/workflows/merge_to_main_staging.yaml

Merge to main staging was failing on installing kubectl when run privately. I've swapped the install method to use the same method that helmfile uses to install kubectl. This should resolve the issue.

chore: Fix kubectl in merge to main staging

---

.github/workflows/merge_to_main_staging.yaml

Reverting the merge to main staging workflow to its previous state until I can get all of the dependencies fixed.

chore: Reverting main to staging workflow for now

---

.devcontainer/devcontainer.json

add syntax highlighter for helm's gotmpl files.

chore: add gotmpl syntax highlighter

---

.github/workflows/helmfile_production_apply.yaml
.github/workflows/helmfile_production_plan.yaml
.github/workflows/helmfile_staging_apply.yaml
.github/workflows/helmfile_staging_plan.yaml

Adding workflow dispatch to helmfile runs so that we can manually run them
Release not working

Adding workflow dispatch to helmfile runs

---

.github/workflows/helmfile_staging_apply_specific_app.yaml

The single helmfile apply workflow will be updated with latest
Part of helmfile and github arc testing

Helmfile staging debug

---

.github/workflows/helmfile_staging_apply_specific_app.yaml
helmfile/overrides/system/github-arc-scaleset.yaml.gotmpl

Setting the individual apply to set the docker_tag env variable. Setting the corresponding helmfile override to also use docker_tag
Re: github arc docker build

Helmfile single apply tag

---

env/staging/fluentbit.yaml

updating the imds version to v2 on staging

---

env/dev/admin-target-group.yaml
env/dev/api-target-group.yaml
env/dev/cwagent/cwagent-deployment-patch.yaml
env/dev/document-download-api-target-group.yaml
env/dev/documentation-target-group.yaml
env/dev/kustomization.yaml

This is our basic working configuration for deploying kustomize and helm to our dev environment.  
Related to this card:
[BCP: Step By Step Document For Building New Environment in same region](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/58)
None.

Dev Environment Kustomize Configurations

---

.github/workflows/merge_to_main_production.yaml

Update the system status lambda

[MANIFEST] : Update merge_to_main_production.yaml

---

.github/workflows/merge_to_main_production.yaml
env/production/kustomization.yaml

Reverts cds-snc/notification-manifests#2657

Revert "[MANIFEST] release-1717528124158"

---

.github/workflows/ipv4-geolocate-webservice-staging.yaml

Adding a staging workflow for the ipv4-geolocate-webservice repository to include newer ARC runner support. The PR for the production PR will come soon afterward.

feat: Added the ipv4 geolocate workflow for staging

---

.github/workflows/helmfile_production_apply.yaml
.github/workflows/helmfile_production_plan.yaml
.github/workflows/merge_to_main_production.yaml

Forgot to add 1password service account tokens to prod runs

[MANIFEST] - Adding service account token for OP

---

.github/workflows/helmfile_production_apply.yaml
.github/workflows/helmfile_production_plan.yaml
.github/workflows/helmfile_staging_apply.yaml
.github/workflows/helmfile_staging_apply_specific_app.yaml
.github/workflows/helmfile_staging_plan.yaml
.github/workflows/merge_to_main_production.yaml
.github/workflows/merge_to_main_staging.yaml

Reverts cds-snc/notification-manifests#2727

[MANIFEST] VPN for Github Actions in Prod

---

.github/workflows/helmfile_production_apply.yaml
.github/workflows/helmfile_production_plan.yaml
.github/workflows/merge_to_main_production.yaml

The 1Password service account has been created with the right permissions. Adding back VPN

[MANIFEST] - Adding vpn back

---

base/notify-api/api-deployment.yaml

[MANIFEST] add FF_TEMPLATE_CATEGORY to api deployment

---

helmfile/charts/xray-daemon/.helmignore
helmfile/charts/xray-daemon/Chart.yaml
helmfile/charts/xray-daemon/templates/NOTES.txt
helmfile/charts/xray-daemon/templates/_helpers.tpl
helmfile/charts/xray-daemon/templates/deployment.yaml
helmfile/charts/xray-daemon/templates/hpa.yaml
helmfile/charts/xray-daemon/templates/ingress.yaml
helmfile/charts/xray-daemon/templates/service.yaml
helmfile/charts/xray-daemon/templates/serviceaccount.yaml
helmfile/charts/xray-daemon/templates/tests/test-connection.yaml
helmfile/helmfile.yaml
helmfile/overrides/system/xray-daemon.yaml.gotmpl

- This should deploy a daemon pod to our staging K8s cluster that monitors any pods configured for Xray (API currently is configured)
[> Give details ex. Security patching, content update, more API pods etc](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/319)

Creating a helm/helmfile deployment for the AWS Xray Daemon

---

base/notify-document-download/document-download-api-deployment.yaml
env/dev/kustomization.yaml

Adding an enviroment variable
Granting doc download api rights to point to the xray daemonset

Adding Xray Env Var

---

.github/actions/diff-env-vars/action.yaml
.github/workflows/ai-code-scanner.yml

Enabled the AI code review action with a few tweaks, given latest changes of our fork (such as moving over to the Azure space which is certified to get PB data). This is restricted to a set of files with the listed extensions and there are others that are explicitly excluded. Anything in-between, not specified by the inclusion pattern, will not be code reviewed by the AI.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/416
The AI code review might comment on this PR, or other ones, once merged. Check the GitHub action log output to make sure it works and that no unexpected output is present.

Add cds-ai-codereviewer github action to k8s repo

---

.github/workflows/merge_to_main_production.yaml

Reverts cds-snc/notification-manifests#2921

[MANIFEST] Added functionality to clear cache after prod deploy

---

.github/workflows/merge_to_main_production.yaml

Reverts cds-snc/notification-manifests#2926

Revert "[MANIFEST] Added functionality to clear cache after prod deploy"

---

.github/PULL_REQUEST_TEMPLATE.md

Added back the PR template meant for the PR bot.
We previously removed the PR template meant for the PR bot as we had no clue what it was doing. Now we know as we crashed the PR bot. 😵
Unrelated, this is a quick fix.
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on staging to verify that performance has not been affected.
Read code suggestions left by the
[cds-ai-codereviewer](https://github.com/cds-snc/cds-ai-codereviewer/) bot. Address
valid suggestions and shortly write down reasons to not address others. To help
with the classification of the comments, please use these reactions on each of the …

Added back the PR template meant for the PR bot.

---

.github/workflows/ai-code-scanner.yml

We removed the API key at the moment for cost reason. Hence this disables the ai code reviewer. We might try it one more week after slight changes to the action and changing region to be more cost effective. Stay tuned.

Disabled the AI code reviewer

---

.github/workflows/merge_to_main_staging.yaml

Debugging cache clear on TF Apply which failed when setting the user name..

debugging cache clear

---

.github/workflows/clear-notify-cache.yaml
.github/workflows/merge_to_main_staging.yaml

Reverting the cache clear workflow config for now.

Cache Clear Revert

---

.github/workflows/merge_to_main_production.yaml

This will fix the invalid workflow config on merge to main prod

[MANIFEST] clear cache fix

---

helmfile/overrides/notify/admin.yaml.gotmpl
helmfile/overrides/notify/api.yaml.gotmpl
helmfile/overrides/notify/document-download.yaml.gotmpl

Helm bug fixes

---

helmfile/charts/notify-celery/templates/deployment-beat.yaml
helmfile/charts/notify-celery/templates/deployment.yaml
helmfile/charts/notify-celery/values.yaml
helmfile/overrides/notify/admin.yaml.gotmpl
helmfile/overrides/notify/api.yaml.gotmpl
helmfile/overrides/notify/document-download.yaml.gotmpl
helmfile/overrides/notify/documentation.yaml.gotmpl

nothing yet! This applies to dev only until we do our helmfile migration in the future.
one (hopefully) last bug fix in our helm code.
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/467

Helmfile Celery Bug Fix

---

helmfile/charts/notify-api/templates/deployment.yaml

Just changed the kustomize code in #3361  😞

fix: log database migration failure in helm deployment too

---

helmfile/overrides/notify/celery.yaml.gotmpl

I didn't do the overrides
Incident

[MANIFEST] Celery memory overrides

---

.github/workflows/helmfile_production_plan.yaml

Debugging helmfile prod diff - we're getting a syntax error on this line... For some reason even though this line looks identical to me, it's showing it as a change so want to see whats up.

[MANIFEST] Helmfile Prod Plan Fix

---

env/dev/kustomization.yaml
env/sandbox/kustomization.yaml
env/staging/kustomization.yaml

fix: Add to kustomization files

---

helmfile/charts/notify-admin/values.yaml
helmfile/overrides/notify/admin.yaml.gotmpl

Hardcode the sending domain to the production one

[MANIFEST] change sending domain

---

scripts/lambdaParamStoreUpdates.sh

setting empty diff to 0 to try and fix broken lambda deploy

updating script

---

.github/workflows/smoke_test.yaml

Switching smoke test user to me since some jerk decided to retire.
Steve doesn't love us anymore

Smoketest fix

---

helmfile/charts/aws-cloudwatch/templates/cwagent-daemonset.yaml

Bump AWS Cloud Watch CPU to 300m to see if this alleviates timeouts.

[MANIFEST] bump aws cw cpu

---

helmfile/overrides/system/aws-cloudwatch-agent.yaml.gotmpl

Updating CW Agent in staging to latest
Incident debugging for failed to write metrics

updating staging aws cloudwatch agent to latest

---

helmfile/charts/notify-database/templates/run-database-job.yaml

This will fix our broken Staging Pipeline DB Migration
see above...
Fixing a bug I merged in the pipeline

Fixing Name in K8s Job

---

.github/actions/db-migration/action.yaml

Fixes our DB Downgrade Manual script
one line in a github action

Github Manual DB Downgrade Fix

---

helmfile/overrides/notify/api.yaml.gotmpl
helmfile/overrides/notify/celery.yaml.gotmpl

Forgot to remove my debugging code from the original PR. Removing repository that points to dev.
Valkey split

Removing repository

---

helmfile/charts/notify-database/templates/run-database-job.yaml

updating a name reference from the api secret store
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/631

updating a name reference from the api secret store

---

helmfile/charts/notify-database/templates/run-database-job.yaml

Reverts cds-snc/notification-manifests#3966

Revert "updating a name reference from the api secret store"
